SimpleLink Graphics Library: Display_api
Display_api
Functions
void Graphics_drawPixelOnDisplay (const Graphics_Display *display, uint16_t x, uint16_t y, uint16_t value)
void Graphics_drawMultiplePixelsOnDisplay (const Graphics_Display *display, uint16_t x, uint16_t y, uint16_t x0, uint16_t count, uint16_t bPP, const uint8_t *data, const uint32_t *palette)
void Graphics_drawHorizontalLineOnDisplay (const Graphics_Display *display, uint16_t x1, uint16_t x2, uint16_t y, uint32_t value)
void Graphics_drawVerticalLineOnDisplay (const Graphics_Display *display, uint16_t x, uint16_t y1, uint16_t y2, uint16_t value)
void Graphics_fillRectangleOnDisplay (const Graphics_Display *display, const Graphics_Rectangle *rect, uint16_t value)
uint32_t Graphics_translateColorOnDisplay (const Graphics_Display *display, uint32_t value)
void Graphics_flushOnDisplay (const Graphics_Display *display)
void Graphics_clearDisplayOnDisplay (const Graphics_Display *display, uint16_t value)
Detailed Description
Function Documentation
Graphics_drawPixelOnDisplay()
void Graphics_drawPixelOnDisplay (const Graphics_Display * display, uint16_t x, uint16_t y, uint16_t value)
Draws a pixel on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x is the X coordinate of the pixel.
y is the Y coordinate of the pixel.
value is the color to draw the pixel.
This function draws a pixel on a display. This assumes that clipping has already been performed.
Returns
None.
References Graphics_Display_Functions::pfnPixelDraw, and Graphics_Display::pFxns.
Referenced by Graphics_drawPixel().
Graphics_drawMultiplePixelsOnDisplay()
void Graphics_drawMultiplePixelsOnDisplay (const Graphics_Display * display, uint16_t x, uint16_t y, uint16_t x0, uint16_t count, uint16_t bPP, const uint8_t * data, const uint32_t * palette)
Draws a horizontal sequence of pixels on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x is the X coordinate of the first pixel.
y is the Y coordinate of the first pixel.
x0 is sub-pixel offset within the pixel data, which is valid for 1 or 4 bit per pixel formats.
count is the number of pixels to draw.
bPP is the number of bits per pixel; must be 1, 4, or 8.
data is a pointer to the pixel data. For 1 and 4 bit per pixel formats, the most significant bit(s) represent the left-most pixel.
palette is a pointer to the palette used to draw the pixels.
This function draws a horizontal sequence of pixels on a display, using the supplied palette. For 1 bit per pixel format, the palette contains pre-translated colors; for 4 and 8 bit per pixel formats, the palette contains 24-bit RGB values that must be translated before being written to the display.
Returns
None.
References Graphics_Display_Functions::pfnPixelDrawMultiple, and Graphics_Display::pFxns.
Graphics_drawHorizontalLineOnDisplay()
void Graphics_drawHorizontalLineOnDisplay (const Graphics_Display * display, uint16_t x1, uint16_t x2, uint16_t y, uint32_t value)
Draws a horizontal line on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x1 is the starting X coordinate of the line.
x2 is the ending X coordinate of the line.
y is the Y coordinate of the line.
value is the color to draw the line.
This function draws a horizontal line on a display. This assumes that clipping has already been performed, and that both end points of the line are within the extents of the display.
Returns
None.
References Graphics_Display_Functions::pfnLineDrawH, and Graphics_Display::pFxns.
Referenced by Graphics_drawLineH().
Graphics_drawVerticalLineOnDisplay()
void Graphics_drawVerticalLineOnDisplay (const Graphics_Display * display, uint16_t x, uint16_t y1, uint16_t y2, uint16_t value)
Draws a vertical line on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x is the X coordinate of the line.
y1 is the starting Y coordinate of the line.
y2 is the ending Y coordinate of the line.
value is the color to draw the line.
This function draws a vertical line on a display. This assumes that clipping has already been performed, and that both end points of the line are within the extents of the display.
Returns
None.
References Graphics_Display_Functions::pfnLineDrawV, and Graphics_Display::pFxns.
Referenced by Graphics_drawLineV().
Graphics_fillRectangleOnDisplay()
void Graphics_fillRectangleOnDisplay (const Graphics_Display * display, const Graphics_Rectangle * rect, uint16_t value)
Fills a rectangle on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
rect is a pointer to the structure describing the rectangle to fill.
value is the color to fill the rectangle.
This function fills a rectangle on the display. This assumes that clipping has already been performed, and that all sides of the rectangle are within the extents of the display.
Returns
None.
References Graphics_Display_Functions::pfnRectFill, and Graphics_Display::pFxns.
Referenced by Graphics_fillRectangle().
Graphics_translateColorOnDisplay()
uint32_t Graphics_translateColorOnDisplay (const Graphics_Display * display, uint32_t value)
Translates a 24-bit RGB color to a display driver-specific color.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
value is the 24-bit RGB color. The least-significant byte is the blue channel, the next byte is the green channel, and the third byte is the red channel.
This function translates a 24-bit RGB color into a value that can be written into the display's frame buffer in order to reproduce that color, or the closest possible approximation of that color.
Returns
Returns the display-driver specific color.
References Graphics_Display_Functions::pfnColorTranslate, and Graphics_Display::pFxns.
Referenced by Graphics_setBackgroundColor(), and Graphics_setForegroundColor().
Graphics_flushOnDisplay()
void Graphics_flushOnDisplay (const Graphics_Display * display)
Flushes cached drawing operations.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
This function flushes any cached drawing operations on a display.
Returns
None.
References Graphics_Display_Functions::pfnFlush, and Graphics_Display::pFxns.
Referenced by Graphics_flushBuffer().
Graphics_clearDisplayOnDisplay()
void Graphics_clearDisplayOnDisplay (const Graphics_Display * display, uint16_t value)
Forces a clear Display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
value is the current background color to fill the screen with.
This function clears the Display
Returns
None.
References Graphics_Display_Functions::pfnClearDisplay, and Graphics_Display::pFxns.
Referenced by Graphics_clearDisplay().
Copyright 2018, Texas Instruments Incorporated