SimpleLink Graphics Library: Checkbox_api
Checkbox_api
Functions
void Graphics_drawCheckBox (const Graphics_Context *context, const Graphics_CheckBox *checkBox)
bool Graphics_isCheckBoxSelected (const Graphics_CheckBox *checkBox, uint16_t x, uint16_t y)
void Graphics_drawSelectedCheckBox (const Graphics_Context *context, const Graphics_CheckBox *checkBox)
void Graphics_drawReleasedCheckBox (const Graphics_Context *context, const Graphics_CheckBox *checkBox)
Detailed Description
Function Documentation
Graphics_drawCheckBox()
void Graphics_drawCheckBox (const Graphics_Context * context, const Graphics_CheckBox * checkBox)
Draws a checkbox.
Parameters
context is a pointer to the drawing context to use.
checkBox is a pointer to the structure containing the extents of the checkbox.
This function draws a checkbox. The checkbox will be created based on the parameters passed in the checkbox struct.
Returns
None.
References AUTO_STRING_LENGTH, Graphics_CheckBox::backgroundColor, Graphics_CheckBox::font, Graphics_Context::font, Graphics_Context::foreground, g_sContext, Graphics_CheckBox::gap, Graphics_drawLine(), Graphics_drawRectangle(), Graphics_drawString(), Graphics_fillRectangle(), Graphics_setFont(), Graphics_setForegroundColor(), Graphics_CheckBox::selected, Graphics_CheckBox::selectedColor, Graphics_CheckBox::text, Graphics_CheckBox::textColor, TRANSPARENT_TEXT, Graphics_CheckBox::xPosition, and Graphics_CheckBox::yPosition.
Graphics_isCheckBoxSelected()
bool Graphics_isCheckBoxSelected (const Graphics_CheckBox * checkBox, uint16_t x, uint16_t y)
Determines if x and y coordinates are contained in the checkbox.
Parameters
checkBox is a pointer to the structure containing the extents of the checkbox.
x x-coordinate to be determined if is inside button
y y-coordinate to be determined if is inside button .
This function determines if x and y coordinates are contains inside checkbox struct.
Returns
true if x and y coordinates are inside checkbox, false if not
References Graphics_CheckBox::font, Graphics_CheckBox::gap, Graphics_CheckBox::numbOfChar, Graphics_CheckBox::xPosition, and Graphics_CheckBox::yPosition.
Graphics_drawSelectedCheckBox()
void Graphics_drawSelectedCheckBox (const Graphics_Context * context, const Graphics_CheckBox * checkBox)
Draws a selected Checkbox.
Parameters
context is a pointer to the drawing context to use.
checkBox is a pointer to the structure containing the extents of the checkBox.
This function draws a selected checkbox using the selected parameters.
Returns
None.
References Graphics_CheckBox::font, Graphics_Context::foreground, g_sContext, Graphics_drawLine(), Graphics_setForegroundColor(), Graphics_CheckBox::selectedColor, Graphics_CheckBox::xPosition, and Graphics_CheckBox::yPosition.
Graphics_drawReleasedCheckBox()
void Graphics_drawReleasedCheckBox (const Graphics_Context * context, const Graphics_CheckBox * checkBox)
Draws a released Checkbox.
Parameters
context is a pointer to the drawing context to use.
checkBox is a pointer to the structure containing the extents of the checkBox.
This function draws a released checkbox using the selected parameters.
Returns
None.
References Graphics_CheckBox::backgroundColor, Graphics_CheckBox::font, Graphics_Context::foreground, g_sContext, Graphics_drawRectangle(), Graphics_fillRectangle(), Graphics_setForegroundColor(), Graphics_CheckBox::textColor, Graphics_CheckBox::xPosition, and Graphics_CheckBox::yPosition.
Copyright 2018, Texas Instruments Incorporated