SimpleLink Graphics Library: Circle_api
Circle_api
Functions
void Graphics_drawCircle (const Graphics_Context *context, int32_t x, int32_t y, int32_t radius)
void Graphics_fillCircle (const Graphics_Context *context, int32_t x, int32_t y, int32_t radius)
Detailed Description
Function Documentation
Graphics_drawCircle()
void Graphics_drawCircle (const Graphics_Context * context, int32_t x, int32_t y, int32_t radius)
Draws a circle.
Parameters
context is a pointer to the drawing context to use.
x is the X coordinate of the center of the circle.
y is the Y coordinate of the center of the circle.
radius is the radius of the circle.
This function draws a circle, utilizing the Bresenham circle drawing algorithm. The extent of the circle is from x - radius to x + radius and y - radius to y + radius, inclusive.
Returns
None.
References Graphics_Context::clipRegion, Graphics_drawPixel(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawRadioButton().
Graphics_fillCircle()
void Graphics_fillCircle (const Graphics_Context * context, int32_t x, int32_t y, int32_t radius)
Draws a filled circle.
Parameters
context is a pointer to the drawing context to use.
x is the X coordinate of the center of the circle.
y is the Y coordinate of the center of the circle.
radius is the radius of the circle.
This function draws a filled circle, utilizing the Bresenham circle drawing algorithm. The extent of the circle is from x - radius to x + radius and y - radius to y + radius, inclusive.
Returns
None.
References Graphics_Context::clipRegion, Graphics_drawLineH(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawRadioButton(), Graphics_drawReleasedRadioButton(), and Graphics_drawSelectedRadioButton().
Copyright 2018, Texas Instruments Incorporated