SimpleLink Graphics Library: ImageButton_api
ImageButton_api
Functions
void Graphics_drawImageButton (const Graphics_Context *context, const Graphics_ImageButton *imageButton)
bool Graphics_isImageButtonSelected (const Graphics_ImageButton *imageButton, uint16_t x, uint16_t y)
void Graphics_drawSelectedImageButton (const Graphics_Context *context, const Graphics_ImageButton *imageButton)
void Graphics_drawReleasedImageButton (const Graphics_Context *context, const Graphics_ImageButton *imageButton)
Detailed Description
Function Documentation
Graphics_drawImageButton()
void Graphics_drawImageButton (const Graphics_Context * context, const Graphics_ImageButton * imageButton)
Draws a ImageButton .
Parameters
context is a pointer to the drawing context to use.
imageButton is a pointer to the structure containing the extents of the ImageButton .
This function draws a ImageButton . The ImageButton will contain the image passed in the ImageButton struct.
Returns
None.
References Graphics_ImageButton::borderWidth, Graphics_Context::font, Graphics_Context::foreground, g_sContext, Graphics_drawImage(), Graphics_fillRectangle(), Graphics_setFont(), Graphics_setForegroundColor(), Graphics_ImageButton::imageHeight, Graphics_ImageButton::imageWidth, Graphics_ImageButton::xPosition, and Graphics_ImageButton::yPosition.
Graphics_isImageButtonSelected()
bool Graphics_isImageButtonSelected (const Graphics_ImageButton * imageButton, uint16_t x, uint16_t y)
Determines if x and y coordinates are contained in ImageButton .
Parameters
imageButton is a pointer to the structure containing the extents of the ImageButton .
x x-coordinate to be determined if is inside ImageButton
y y-coordinate to be determined if is inside ImageButton
This function determines if x and y coordinates are contains inside ImageButton
Returns
true if x and y coordinates are inside ImageButton, false if not
References Graphics_ImageButton::borderWidth, Graphics_ImageButton::imageHeight, Graphics_ImageButton::imageWidth, Graphics_ImageButton::xPosition, and Graphics_ImageButton::yPosition.
Graphics_drawSelectedImageButton()
void Graphics_drawSelectedImageButton (const Graphics_Context * context, const Graphics_ImageButton * imageButton)
Draws a selected ImageButton .
Parameters
context is a pointer to the drawing context to use.
imageButton is a pointer to the structure containing the extents of the ImageButton .
This function draws a ImageButton using the selected parameters.
Returns
None.
References Graphics_ImageButton::borderWidth, Graphics_Context::font, Graphics_Context::foreground, g_sContext, Graphics_drawImage(), Graphics_fillRectangle(), Graphics_setFont(), Graphics_setForegroundColor(), Graphics_ImageButton::imageHeight, Graphics_ImageButton::imageWidth, Graphics_ImageButton::xPosition, and Graphics_ImageButton::yPosition.
Graphics_drawReleasedImageButton()
void Graphics_drawReleasedImageButton (const Graphics_Context * context, const Graphics_ImageButton * imageButton)
Draws a released ImageButton .
Parameters
context is a pointer to the drawing context to use.
imageButton is a pointer to the structure containing the extents of the ImageButton .
This function draws a ImageButton using the released parameters.
Returns
None.
References Graphics_ImageButton::borderWidth, Graphics_Context::font, Graphics_Context::foreground, g_sContext, Graphics_drawImage(), Graphics_fillRectangle(), Graphics_setFont(), Graphics_setForegroundColor(), Graphics_ImageButton::imageHeight, Graphics_ImageButton::imageWidth, Graphics_ImageButton::xPosition, and Graphics_ImageButton::yPosition.
Copyright 2018, Texas Instruments Incorporated