SimpleLink Graphics Library: Primitives_api
Primitives_api
Data Structures
struct Graphics_Image
This structure defines the characteristics of a Bitmap Image.
struct Graphics_Rectangle
struct Graphics_Display_Functions
This structure defines the implementation of a display driver.
struct Graphics_Display
This structure defines the characteristics of a display driver.
struct Graphics_Font
This structure describes a font used for drawing text onto the screen.
struct Graphics_FontEx
struct Graphics_Context
Macros
#define min(a, b) (((a) < (b)) ? (a) : (b))
#define max(a, b) (((a) < (b)) ? (b) : (a))
#define ClrAliceBlue GRAPHICS_COLOR_ALICE_BLUE
#define ClrAntiqueWhite GRAPHICS_COLOR_ANTIQUE_WHITE
#define ClrAqua GRAPHICS_COLOR_AQUA
#define ClrAquamarine GRAPHICS_COLOR_AQUAMARINE
#define ClrAzure GRAPHICS_COLOR_AZURE
#define ClrBeige GRAPHICS_COLOR_BEIGE
#define ClrBisque GRAPHICS_COLOR_BISQUE
#define ClrBlack GRAPHICS_COLOR_BLACK
#define ClrBlack GRAPHICS_COLOR_BLACK
#define ClrBlanchedAlmond GRAPHICS_COLOR_BLANCHED_ALMOND
#define ClrBlue GRAPHICS_COLOR_BLUE
#define ClrBlueViolet GRAPHICS_COLOR_BLUE_VIOLET
#define ClrBrown GRAPHICS_COLOR_BROWN
#define ClrBurlyWood GRAPHICS_COLOR_BURLY_WOOD
#define ClrCadetBlue GRAPHICS_COLOR_CADET_BLUE
#define ClrChartreuse GRAPHICS_COLOR_CHARTREUSE
#define ClrChocolate GRAPHICS_COLOR_CHOCOLATE
#define ClrCoral GRAPHICS_COLOR_CORAL
#define ClrCornflowerBlue GRAPHICS_COLOR_CORNFLOWER_BLUE
#define ClrCornsilk GRAPHICS_COLOR_CORNSILK
#define ClrCrimson GRAPHICS_COLOR_CRIMSON
#define ClrCyan GRAPHICS_COLOR_CYAN
#define ClrDarkBlue GRAPHICS_COLOR_DARK_BLUE
#define ClrDarkCyan GRAPHICS_COLOR_DARK_CYAN
#define ClrDarkGoldenrod GRAPHICS_COLOR_DARK_GOLDENROD
#define ClrDarkGray GRAPHICS_COLOR_DARK_GRAY
#define ClrDarkGreen GRAPHICS_COLOR_DARK_GREEN
#define ClrDarkKhaki GRAPHICS_COLOR_DARK_KHAKI
#define ClrDarkMagenta GRAPHICS_COLOR_DARK_MAGENTA
#define ClrDarkOliveGreen GRAPHICS_COLOR_DARK_OLIVE_GREEN
#define ClrDarkOrange GRAPHICS_COLOR_DARK_ORANGE
#define ClrDarkOrchid GRAPHICS_COLOR_DARK_ORCHID
#define ClrDarkRed GRAPHICS_COLOR_DARK_RED
#define ClrDarkSalmon GRAPHICS_COLOR_DARK_SALMON
#define ClrDarkSeaGreen GRAPHICS_COLOR_DARK_SEA_GREEN
#define ClrDarkSlateBlue GRAPHICS_COLOR_DARK_SLATE_BLUE
#define ClrDarkSlateGray GRAPHICS_COLOR_DARK_SLATE_GRAY
#define ClrDarkTurquoise GRAPHICS_COLOR_DARK_TURQUOISE
#define ClrDarkViolet GRAPHICS_COLOR_DARK_VIOLET
#define ClrDeepPink GRAPHICS_COLOR_DEEP_PINK
#define ClrDeepSkyBlue GRAPHICS_COLOR_DEEP_SKY_BLUE
#define ClrDimGray GRAPHICS_COLOR_DIM_GRAY
#define ClrDodgerBlue GRAPHICS_COLOR_DODGER_BLUE
#define ClrFireBrick GRAPHICS_COLOR_FIRE_BRICK
#define ClrFloralWhite GRAPHICS_COLOR_FLORAL_WHITE
#define ClrForestGreen GRAPHICS_COLOR_FOREST_GREEN
#define ClrFuchsia GRAPHICS_COLOR_FUCHSIA
#define ClrGainsboro GRAPHICS_COLOR_GAINSBORO
#define ClrGhostWhite GRAPHICS_COLOR_GHOST_WHITE
#define ClrGold GRAPHICS_COLOR_GOLD
#define ClrGoldenrod GRAPHICS_COLOR_GOLDENRON
#define ClrGray GRAPHICS_COLOR_GRAY
#define ClrGreen GRAPHICS_COLOR_GREEN
#define ClrGreenYellow GRAPHICS_COLOR_GREEN_YELLOW
#define ClrHoneydew GRAPHICS_COLOR_HONEYDEW
#define ClrHotPink GRAPHICS_COLOR_HOT_PINK
#define ClrIndianRed GRAPHICS_COLOR_INDIAN_RED
#define ClrIndigo GRAPHICS_COLOR_INDIGO
#define ClrIvory GRAPHICS_COLOR_IVORY
#define ClrKhaki GRAPHICS_COLOR_KHAKI
#define ClrLavender GRAPHICS_COLOR_LAVENDER
#define ClrLavenderBlush GRAPHICS_COLOR_LAVENDER_BLUSH
#define ClrLawnGreen GRAPHICS_COLOR_LAWN_GREEN
#define ClrLemonChiffon GRAPHICS_COLOR_LEMON_CHIFFON
#define ClrLightBlue GRAPHICS_COLOR_LIGHT_BLUE
#define ClrLightCoral GRAPHICS_COLOR_LIGHT_CORAL
#define ClrLightCyan GRAPHICS_COLOR_LIGHT_CYAN
#define ClrLightGoldenrodYellow GRAPHICS_COLOR_LIGHT_GOLDENRON_YELLOW
#define ClrLightGreen GRAPHICS_COLOR_LIGHT_GREEN
#define ClrLightGrey GRAPHICS_COLOR_LIGHT_GRAY
#define ClrLightPink GRAPHICS_COLOR_LIGHT_PINK
#define ClrLightSalmon GRAPHICS_COLOR_LIGHT_SALMON
#define ClrLightSeaGreen GRAPHICS_COLOR_LIGHT_SEA_GREEN
#define ClrLightSkyBlue GRAPHICS_COLOR_LIGHT_SKY_BLUE
#define ClrLightSlateGray GRAPHICS_COLOR_LIGHT_SLATE_GRAY
#define ClrLightSteelBlue GRAPHICS_COLOR_LIGHT_STEEL_BLUE
#define ClrLightYellow GRAPHICS_COLOR_LIGHT_YELLOW
#define ClrLime GRAPHICS_COLOR_LIME
#define ClrLimeGreen GRAPHICS_COLOR_LIME_GREEN
#define ClrLinen GRAPHICS_COLOR_LINEN
#define ClrMagenta GRAPHICS_COLOR_MAGENTA
#define ClrMaroon GRAPHICS_COLOR_MAROON
#define ClrMediumAquamarine GRAPHICS_COLOR_MEDIUM_AQUAMARINE
#define ClrMediumBlue GRAPHICS_COLOR_MEDIUM_BLUE
#define ClrMediumOrchid GRAPHICS_COLOR_MEDIUM_ORCHID
#define ClrMediumPurple GRAPHICS_COLOR_MEDIUM_PURPLE
#define ClrMediumSeaGreen GRAPHICS_COLOR_MEDIUM_SEA_GREEN
#define ClrMediumSlateBlue GRAPHICS_COLOR_MEDIUM_SLATE_BLUE
#define ClrMediumSpringGreen GRAPHICS_COLOR_MEDIUM_SPRING_GREEN
#define ClrMediumTurquoise GRAPHICS_COLOR_MEDIUM_TURQUOISE
#define ClrMediumVioletRed GRAPHICS_COLOR_MEDIUM_VIOLET_RED
#define ClrMidnightBlue GRAPHICS_COLOR_MIGNIGHT_BLUE
#define ClrMintCream GRAPHICS_COLOR_MINT_CREAM
#define ClrMistyRose GRAPHICS_COLOR_MISTY_ROSE
#define ClrMoccasin GRAPHICS_COLOR_MOCCASIN
#define ClrNavajoWhite GRAPHICS_COLOR_NAVAJO_WHITE
#define ClrNavy GRAPHICS_COLOR_NAVY
#define ClrOldLace GRAPHICS_COLOR_OLD_LACE
#define ClrOlive GRAPHICS_COLOR_OLIVE
#define ClrOliveDrab GRAPHICS_COLOR_OLIVE_DRAB
#define ClrOrange GRAPHICS_COLOR_ORANGE
#define ClrOrangeRed GRAPHICS_COLOR_ORANGE_RED
#define ClrOrchid GRAPHICS_COLOR_ORCHID
#define ClrPaleGoldenrod GRAPHICS_COLOR_PALE_GOLDENRON
#define ClrPaleGreen GRAPHICS_COLOR_PALE_GREEN
#define ClrPaleTurquoise GRAPHICS_COLOR_PALE_TURQUOISE
#define ClrPaleVioletRed GRAPHICS_COLOR_PALE_VIOLET_RED
#define ClrPapayaWhip GRAPHICS_COLOR_PAPAYA_WHIP
#define ClrPeachPuff GRAPHICS_COLOR_PEACH_PUFF
#define ClrPeru GRAPHICS_COLOR_PERU
#define ClrPink GRAPHICS_COLOR_PINK
#define ClrPlum GRAPHICS_COLOR_PLUM
#define ClrPowderBlue GRAPHICS_COLOR_POWDER_BLUE
#define ClrPurple GRAPHICS_COLOR_PURPLE
#define ClrRed GRAPHICS_COLOR_RED
#define ClrRosyBrown GRAPHICS_COLOR_ROSY_BROWN
#define ClrRoyalBlue GRAPHICS_COLOR_ROYAL_BLUE
#define ClrSaddleBrown GRAPHICS_COLOR_SADDLE_BROWN
#define ClrSalmon GRAPHICS_COLOR_SALMON
#define ClrSandyBrown GRAPHICS_COLOR_SANDY_BROWN
#define ClrSeaGreen GRAPHICS_COLOR_SEA_GREEN
#define ClrSeashell GRAPHICS_COLOR_SEASHELL
#define ClrSienna GRAPHICS_COLOR_SIENNA
#define ClrSilver GRAPHICS_COLOR_SILVER
#define ClrSkyBlue GRAPHICS_COLOR_SKY_BLUE
#define ClrSlateBlue GRAPHICS_COLOR_SLATE_BLUE
#define ClrSlateGray GRAPHICS_COLOR_SLATE_GRAY
#define ClrSnow GRAPHICS_COLOR_SNOW
#define ClrSpringGreen GRAPHICS_COLOR_SPRING_GREEN
#define ClrSteelBlue GRAPHICS_COLOR_STEEL_BLUE
#define ClrTan GRAPHICS_COLOR_TAN
#define ClrTeal GRAPHICS_COLOR_TEAL
#define ClrThistle GRAPHICS_COLOR_THISTLE
#define ClrTomato GRAPHICS_COLOR_TOMATO
#define ClrTurquoise GRAPHICS_COLOR_TURQUOISE
#define ClrViolet GRAPHICS_COLOR_VIOLET
#define ClrWheat GRAPHICS_COLOR_WHEAT
#define ClrWhite GRAPHICS_COLOR_WHITE
#define ClrWhiteSmoke GRAPHICS_COLOR_WHITE_SMOKE
#define ClrYellow GRAPHICS_COLOR_YELLOW
#define ClrYellowGreen GRAPHICS_COLOR_YELLOW_GREEN
#define FONT_FMT_UNCOMPRESSED GRAPHICS_FONT_FMT_UNCOMPRESSED
#define FONT_FMT_PIXEL_RLE GRAPHICS_FONT_FMT_PIXEL_RLE
#define FONT_EX_MARKER GRAPHICS_FONT_EX_MARKER
#define FONT_FMT_EX_UNCOMPRESSED GRAPHICS_FONT_FMT_EX_UNCOMPRESSED
#define FONT_FMT_EX_PIXEL_RLE GRAPHICS_FONT_FMT_EX_PIXEL_RLE
#define AUTO_STRING_LENGTH GRAPHICS_AUTO_STRING_LENGTH
#define OPAQUE_TEXT GRAPHICS_OPAQUE_TEXT
#define TRANSPARENT_TEXT GRAPHICS_TRANSPARENT_TEXT
#define IMAGE_FMT_1BPP_UNCOMP GRAPHICS_IMAGE_FMT_1BPP_UNCOMP
#define IMAGE_FMT_2BPP_UNCOMP GRAPHICS_IMAGE_FMT_2BPP_UNCOMP
#define IMAGE_FMT_2BPP_UNCOMP GRAPHICS_IMAGE_FMT_2BPP_UNCOMP
#define IMAGE_FMT_4BPP_UNCOMP GRAPHICS_IMAGE_FMT_4BPP_UNCOMP
#define IMAGE_FMT_8BPP_UNCOMP GRAPHICS_IMAGE_FMT_8BPP_UNCOMP
#define IMAGE_FMT_1BPP_COMP_RLE4 GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE4
#define IMAGE_FMT_4BPP_COMP_RLE4 GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE4
#define IMAGE_FMT_1BPP_COMP_RLE7 GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE7
#define IMAGE_FMT_1BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE8
#define IMAGE_FMT_2BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE8
#define IMAGE_FMT_4BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE8
#define IMAGE_FMT_8BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_8BPP_COMP_RLE8
#define IMAGE_FMT_8BPP_COMP_RLEBLEND GRAPHICS_IMAGE_FMT_8BPP_COMP_RLEBLEND
#define tFontEx Graphics_FontEx
#define tFont Graphics_Font
#define tDisplay Graphics_Display
#define tRectangle Graphics_Rectangle
#define tImage Graphics_Image
#define tContext Graphics_Context
#define sXMax xMax
#define sXMin xMin
#define sYMax yMax
#define sYMin yMin
#define GrCircleDraw Graphics_drawCircle
#define GrCircleFill Graphics_fillCircle
#define GrContextClipRegionSet Graphics_setClipRegion
#define GrContextInit Graphics_initContext
#define GrImageDraw Graphics_drawImage
#define GrLineDraw Graphics_drawLine
#define GrLineDrawH Graphics_drawLineH
#define GrLineDrawV Graphics_drawLineV
#define GrRectDraw Graphics_drawRectangle
#define GrRectFill Graphics_fillRectangle
#define GrStringDraw Graphics_drawString
#define GrStringWidthGet Graphics_getStringWidth
#define GrRectOverlapCheck Graphics_isOverlappingRectangle
#define GrRectIntersectGet Graphics_getRectangleIntersection
#define GrContextBackgroundSet Graphics_setBackgroundColor
#define GrContextBackgroundSetTranslated Graphics_setBackgroundColorTranslated
#define GrContextDpyWidthGet Graphics_getDisplayWidth
#define GrContextDpyHeightGet Graphics_getDisplayHeight
#define GrContextFontSet Graphics_setFont
#define GrContextForegroundSet Graphics_setForegroundColor
#define GrContextForegroundSetTranslated Graphics_setForegroundColorTranslated
#define GrFlush Graphics_flushBuffer
#define GrClearDisplay Graphics_clearDisplay
#define GrFontBaselineGet Graphics_getFontBaseline
#define GrFontHeightGet Graphics_getFontHeight
#define GrFontMaxWidthGet Graphics_getFontMaxWidth
#define GrImageColorsGet Graphics_getImageColors
#define GrImageHeightGet Graphics_getImageHeight
#define GrImageWidthGet Graphics_getImageWidth
#define GrOffScreen1BPPSize Graphics_getOffscreen1BppImageSize
#define GrOffScreen4BPPSize Graphics_getOffscreen4BppImageSize
#define GrOffScreen8BPPSize Graphics_getOffscreen8BppImageSize
#define GrPixelDraw Graphics_drawPixel
#define GrStringBaselineGet Graphics_getStringBaseline
#define GrStringDrawCentered Graphics_drawStringCentered
#define GrStringHeightGet Graphics_getStringHeight
#define GrStringMaxWidthGet Graphics_getStringMaxWidth
#define DpyColorTranslate Graphics_translateColorOnDisplay
#define DpyFlush Graphics_flushOnDisplay
#define DpyClearDisplay Graphics_clearDisplayOnDisplay
#define DpyHeightGet Graphics_getHeightOfDisplay
#define DpyLineDrawH Graphics_drawHorizontalLineOnDisplay
#define DpyLineDrawV Graphics_drawVerticalLineOnDisplay
#define DpyPixelDraw Graphics_drawPixelOnDisplay
#define DpyPixelDrawMultiple Graphics_drawMultiplePixelsOnDisplay
#define DpyRectFill Graphics_fillRectangleOnDisplay
#define DpyWidthGet Graphics_getWidthOfDisplay
#define GrRectContainsPoint Graphics_isPointWithinRectangle
#define GRAPHICS_FONT_FMT_UNCOMPRESSED 0x00
Indicates that the font data is stored in an uncompressed format.
#define GRAPHICS_FONT_FMT_PIXEL_RLE 0x01
Indicates that the font data is stored using a pixel-based RLE format.
#define GRAPHICS_FONT_EX_MARKER 0x80
#define GRAPHICS_FONT_FMT_EX_UNCOMPRESSED
#define GRAPHICS_FONT_FMT_EX_PIXEL_RLE
#define GRAPHICS_AUTO_STRING_LENGTH -1
#define GRAPHICS_OPAQUE_TEXT 1
#define GRAPHICS_TRANSPARENT_TEXT 0
#define GRAPHICS_IMAGE_FMT_1BPP_UNCOMP 0x01
#define GRAPHICS_IMAGE_FMT_2BPP_UNCOMP 0x02
#define GRAPHICS_IMAGE_FMT_4BPP_UNCOMP 0x04
#define GRAPHICS_IMAGE_FMT_8BPP_UNCOMP 0x08
#define GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE4 0x41
#define GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE4 0x42
#define GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE4 0x44
#define GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE7 0x71
#define GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE8 0x81
#define GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE8 0x82
#define GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE8 0x84
#define GRAPHICS_IMAGE_FMT_8BPP_COMP_RLE8 0x88
#define GRAPHICS_IMAGE_FMT_8BPP_COMP_RLEBLEND 0x28
#define GRAPHICS_COLOR_ALICE_BLUE 0x00F0F8FF
#define GRAPHICS_COLOR_ANTIQUE_WHITE 0x00FAEBD7
#define GRAPHICS_COLOR_AQUA 0x0000FFFF
#define GRAPHICS_COLOR_AQUAMARINE 0x007FFFD4
#define GRAPHICS_COLOR_AZURE 0x00F0FFFF
#define GRAPHICS_COLOR_BEIGE 0x00F5F5DC
#define GRAPHICS_COLOR_BISQUE 0x00FFE4C4
#define GRAPHICS_COLOR_BLACK 0x00000000
#define GRAPHICS_COLOR_BLACK 0x00000000
#define GRAPHICS_COLOR_BLANCHED_ALMOND 0x00FFEBCD
#define GRAPHICS_COLOR_BLUE 0x000000FF
#define GRAPHICS_COLOR_BLUE_VIOLET 0x008A2BE2
#define GRAPHICS_COLOR_BROWN 0x00A52A2A
#define GRAPHICS_COLOR_BURLY_WOOD 0x00DEB887
#define GRAPHICS_COLOR_CADET_BLUE 0x005F9EA0
#define GRAPHICS_COLOR_CHARTREUSE 0x007FFF00
#define GRAPHICS_COLOR_CHOCOLATE 0x00D2691E
#define GRAPHICS_COLOR_CORAL 0x00FF7F50
#define GRAPHICS_COLOR_CORNFLOWER_BLUE 0x006495ED
#define GRAPHICS_COLOR_CORNSILK 0x00FFF8DC
#define GRAPHICS_COLOR_CRIMSON 0x00DC143C
#define GRAPHICS_COLOR_CYAN 0x0000FFFF
#define GRAPHICS_COLOR_DARK_BLUE 0x0000008B
#define GRAPHICS_COLOR_DARK_CYAN 0x00008B8B
#define GRAPHICS_COLOR_DARK_GOLDENROD 0x00B8860B
#define GRAPHICS_COLOR_DARK_GRAY 0x00A9A9A9
#define GRAPHICS_COLOR_DARK_GREEN 0x00006400
#define GRAPHICS_COLOR_DARK_KHAKI 0x00BDB76B
#define GRAPHICS_COLOR_DARK_MAGENTA 0x008B008B
#define GRAPHICS_COLOR_DARK_OLIVE_GREEN 0x00556B2F
#define GRAPHICS_COLOR_DARK_ORANGE 0x00FF8C00
#define GRAPHICS_COLOR_DARK_ORCHID 0x009932CC
#define GRAPHICS_COLOR_DARK_RED 0x008B0000
#define GRAPHICS_COLOR_DARK_SALMON 0x00E9967A
#define GRAPHICS_COLOR_DARK_SEA_GREEN 0x008FBC8F
#define GRAPHICS_COLOR_DARK_SLATE_BLUE 0x00483D8B
#define GRAPHICS_COLOR_DARK_SLATE_GRAY 0x002F4F4F
#define GRAPHICS_COLOR_DARK_TURQUOISE 0x0000CED1
#define GRAPHICS_COLOR_DARK_VIOLET 0x009400D3
#define GRAPHICS_COLOR_DEEP_PINK 0x00FF1493
#define GRAPHICS_COLOR_DEEP_SKY_BLUE 0x0000BFFF
#define GRAPHICS_COLOR_DIM_GRAY 0x00696969
#define GRAPHICS_COLOR_DODGER_BLUE 0x001E90FF
#define GRAPHICS_COLOR_FIRE_BRICK 0x00B22222
#define GRAPHICS_COLOR_FLORAL_WHITE 0x00FFFAF0
#define GRAPHICS_COLOR_FOREST_GREEN 0x00228B22
#define GRAPHICS_COLOR_FUCHSIA 0x00FF00FF
#define GRAPHICS_COLOR_GAINSBORO 0x00DCDCDC
#define GRAPHICS_COLOR_GHOST_WHITE 0x00F8F8FF
#define GRAPHICS_COLOR_GOLD 0x00FFD700
#define GRAPHICS_COLOR_GOLDENRON 0x00DAA520
#define GRAPHICS_COLOR_GRAY 0x00808080
#define GRAPHICS_COLOR_GREEN 0x00008000
#define GRAPHICS_COLOR_GREEN_YELLOW 0x00ADFF2F
#define GRAPHICS_COLOR_HONEYDEW 0x00F0FFF0
#define GRAPHICS_COLOR_HOT_PINK 0x00FF69B4
#define GRAPHICS_COLOR_INDIAN_RED 0x00CD5C5C
#define GRAPHICS_COLOR_INDIGO 0x004B0082
#define GRAPHICS_COLOR_IVORY 0x00FFFFF0
#define GRAPHICS_COLOR_KHAKI 0x00F0E68C
#define GRAPHICS_COLOR_LAVENDER 0x00E6E6FA
#define GRAPHICS_COLOR_LAVENDER_BLUSH 0x00FFF0F5
#define GRAPHICS_COLOR_LAWN_GREEN 0x007CFC00
#define GRAPHICS_COLOR_LEMON_CHIFFON 0x00FFFACD
#define GRAPHICS_COLOR_LIGHT_BLUE 0x00ADD8E6
#define GRAPHICS_COLOR_LIGHT_CORAL 0x00F08080
#define GRAPHICS_COLOR_LIGHT_CYAN 0x00E0FFFF
#define GRAPHICS_COLOR_LIGHT_GOLDENRON_YELLOW 0x00FAFAD2
#define GRAPHICS_COLOR_LIGHT_GREEN 0x0090EE90
#define GRAPHICS_COLOR_LIGHT_GRAY 0x00D3D3D3
#define GRAPHICS_COLOR_LIGHT_PINK 0x00FFB6C1
#define GRAPHICS_COLOR_LIGHT_SALMON 0x00FFA07A
#define GRAPHICS_COLOR_LIGHT_SEA_GREEN 0x0020B2AA
#define GRAPHICS_COLOR_LIGHT_SKY_BLUE 0x0087CEFA
#define GRAPHICS_COLOR_LIGHT_SLATE_GRAY 0x00778899
#define GRAPHICS_COLOR_LIGHT_STEEL_BLUE 0x00B0C4DE
#define GRAPHICS_COLOR_LIGHT_YELLOW 0x00FFFFE0
#define GRAPHICS_COLOR_LIME 0x0000FF00
#define GRAPHICS_COLOR_LIME_GREEN 0x0032CD32
#define GRAPHICS_COLOR_LINEN 0x00FAF0E6
#define GRAPHICS_COLOR_MAGENTA 0x00FF00FF
#define GRAPHICS_COLOR_MAROON 0x00800000
#define GRAPHICS_COLOR_MEDIUM_AQUAMARINE 0x0066CDAA
#define GRAPHICS_COLOR_MEDIUM_BLUE 0x000000CD
#define GRAPHICS_COLOR_MEDIUM_ORCHID 0x00BA55D3
#define GRAPHICS_COLOR_MEDIUM_PURPLE 0x009370DB
#define GRAPHICS_COLOR_MEDIUM_SEA_GREEN 0x003CB371
#define GRAPHICS_COLOR_MEDIUM_SLATE_BLUE 0x007B68EE
#define GRAPHICS_COLOR_MEDIUM_SPRING_GREEN 0x0000FA9A
#define GRAPHICS_COLOR_MEDIUM_TURQUOISE 0x0048D1CC
#define GRAPHICS_COLOR_MEDIUM_VIOLET_RED 0x00C71585
#define GRAPHICS_COLOR_MIGNIGHT_BLUE 0x00191970
#define GRAPHICS_COLOR_MINT_CREAM 0x00F5FFFA
#define GRAPHICS_COLOR_MISTY_ROSE 0x00FFE4E1
#define GRAPHICS_COLOR_MOCCASIN 0x00FFE4B5
#define GRAPHICS_COLOR_NAVAJO_WHITE 0x00FFDEAD
#define GRAPHICS_COLOR_NAVY 0x00000080
#define GRAPHICS_COLOR_OLD_LACE 0x00FDF5E6
#define GRAPHICS_COLOR_OLIVE 0x00808000
#define GRAPHICS_COLOR_OLIVE_DRAB 0x006B8E23
#define GRAPHICS_COLOR_ORANGE 0x00FFA500
#define GRAPHICS_COLOR_ORANGE_RED 0x00FF4500
#define GRAPHICS_COLOR_ORCHID 0x00DA70D6
#define GRAPHICS_COLOR_PALE_GOLDENRON 0x00EEE8AA
#define GRAPHICS_COLOR_PALE_GREEN 0x0098FB98
#define GRAPHICS_COLOR_PALE_TURQUOISE 0x00AFEEEE
#define GRAPHICS_COLOR_PALE_VIOLET_RED 0x00DB7093
#define GRAPHICS_COLOR_PAPAYA_WHIP 0x00FFEFD5
#define GRAPHICS_COLOR_PEACH_PUFF 0x00FFDAB9
#define GRAPHICS_COLOR_PERU 0x00CD853F
#define GRAPHICS_COLOR_PINK 0x00FFC0CB
#define GRAPHICS_COLOR_PLUM 0x00DDA0DD
#define GRAPHICS_COLOR_POWDER_BLUE 0x00B0E0E6
#define GRAPHICS_COLOR_PURPLE 0x00800080
#define GRAPHICS_COLOR_RED 0x00FF0000
#define GRAPHICS_COLOR_ROSY_BROWN 0x00BC8F8F
#define GRAPHICS_COLOR_ROYAL_BLUE 0x004169E1
#define GRAPHICS_COLOR_SADDLE_BROWN 0x008B4513
#define GRAPHICS_COLOR_SALMON 0x00FA8072
#define GRAPHICS_COLOR_SANDY_BROWN 0x00F4A460
#define GRAPHICS_COLOR_SEA_GREEN 0x002E8B57
#define GRAPHICS_COLOR_SEASHELL 0x00FFF5EE
#define GRAPHICS_COLOR_SIENNA 0x00A0522D
#define GRAPHICS_COLOR_SILVER 0x00C0C0C0
#define GRAPHICS_COLOR_SKY_BLUE 0x0087CEEB
#define GRAPHICS_COLOR_SLATE_BLUE 0x006A5ACD
#define GRAPHICS_COLOR_SLATE_GRAY 0x00708090
#define GRAPHICS_COLOR_SNOW 0x00FFFAFA
#define GRAPHICS_COLOR_SPRING_GREEN 0x0000FF7F
#define GRAPHICS_COLOR_STEEL_BLUE 0x004682B4
#define GRAPHICS_COLOR_TAN 0x00D2B48C
#define GRAPHICS_COLOR_TEAL 0x00008080
#define GRAPHICS_COLOR_THISTLE 0x00D8BFD8
#define GRAPHICS_COLOR_TOMATO 0x00FF6347
#define GRAPHICS_COLOR_TURQUOISE 0x0040E0D0
#define GRAPHICS_COLOR_VIOLET 0x00EE82EE
#define GRAPHICS_COLOR_WHEAT 0x00F5DEB3
#define GRAPHICS_COLOR_WHITE 0x00FFFFFF
#define GRAPHICS_COLOR_WHITE_SMOKE 0x00F5F5F5
#define GRAPHICS_COLOR_YELLOW 0x00FFFF00
#define GRAPHICS_COLOR_YELLOW_GREEN 0x009ACD32
#define ClrRedMask 0x00FF0000
#define ClrRedShift 16
#define ClrGreenMask 0x0000FF00
#define ClrGreenShift 8
#define ClrBlueMask 0x000000FF
#define ClrBlueShift 0
#define GrLangZhPRC 0x0804
#define GrLangZhTW 0x0404
#define GrLangEnUS 0x0409
#define GrLangEnUK 0x0809
#define GrLangEnAUS 0x0C09
#define GrLangEnCA 0x1009
#define GrLangEnNZ 0x1409
#define GrLangFr 0x040C
#define GrLangDe 0x0407
#define GrLangHi 0x0439
#define GrLangIt 0x0410
#define GrLangJp 0x0411
#define GrLangKo 0x0412
#define GrLangEsMX 0x080A
#define GrLangEsSP 0x0C0A
#define GrLangSwKE 0x0441
#define GrLangUrIN 0x0820
#define GrLangUrPK 0x0420
Typedefs
typedef struct Graphics_Image Graphics_Image
This structure defines the characteristics of a Bitmap Image.
typedef struct Graphics_Rectangle Graphics_Rectangle
typedef struct Graphics_Display Graphics_Display
typedef struct Graphics_Display_Functions Graphics_Display_Functions
This structure defines the implementation of a display driver.
typedef struct Graphics_Font Graphics_Font
This structure describes a font used for drawing text onto the screen.
typedef struct Graphics_FontEx Graphics_FontEx
typedef struct Graphics_Context Graphics_Context
Functions
void Graphics_drawCircle (const Graphics_Context *context, int32_t x, int32_t y, int32_t lRadius)
void Graphics_fillCircle (const Graphics_Context *context, int32_t x, int32_t y, int32_t lRadius)
void Graphics_setClipRegion (Graphics_Context *context, Graphics_Rectangle *rect)
void Graphics_initContext (Graphics_Context *context, Graphics_Display *display, const Graphics_Display_Functions *pFxns)
void Graphics_drawImage (const Graphics_Context *context, const Graphics_Image *pBitmap, int16_t x, int16_t y)
void Graphics_drawLine (const Graphics_Context *context, int32_t x1, int32_t y1, int32_t x2, int32_t y2)
void Graphics_drawLineH (const Graphics_Context *context, int32_t x1, int32_t x2, int32_t y)
void Graphics_drawLineV (const Graphics_Context *context, int32_t x, int32_t y1, int32_t y2)
void Graphics_drawRectangle (const Graphics_Context *context, const Graphics_Rectangle *rect)
void Graphics_fillRectangle (const Graphics_Context *context, const Graphics_Rectangle *rect)
void Graphics_drawString (const Graphics_Context *context, int8_t *string, int32_t lLength, int32_t x, int32_t y, bool opaque)
int32_t Graphics_getStringWidth (const Graphics_Context *context, const int8_t *string, int32_t lLength)
int32_t Graphics_isOverlappingRectangle (Graphics_Rectangle *psRect1, Graphics_Rectangle *psRect2)
int32_t Graphics_getRectangleIntersection (Graphics_Rectangle *psRect1, Graphics_Rectangle *psRect2, Graphics_Rectangle *psIntersect)
void Graphics_setBackgroundColor (Graphics_Context *context, int32_t value)
uint16_t Graphics_getDisplayWidth (Graphics_Context *context)
uint16_t Graphics_getDisplayHeight (Graphics_Context *context)
void Graphics_setFont (Graphics_Context *context, const Graphics_Font *font)
uint8_t Graphics_getFontBaseline (const Graphics_Font *font)
void Graphics_setForegroundColor (Graphics_Context *context, int32_t value)
void Graphics_setForegroundColorTranslated (Graphics_Context *context, int32_t value)
uint8_t Graphics_getFontHeight (const Graphics_Font *font)
uint8_t Graphics_getFontMaxWidth (const Graphics_Font *font)
uint16_t Graphics_getImageColors (const Graphics_Image *image)
uint16_t Graphics_getImageHeight (const Graphics_Image *image)
uint16_t Graphics_getImageWidth (const Graphics_Image *image)
uint32_t Graphics_getOffscreen1BppImageSize (uint16_t width, uint16_t height)
uint32_t Graphics_getOffscreen4BppImageSize (uint16_t width, uint16_t height)
uint32_t Graphics_getOffScreen8BPPSize (uint16_t width, uint16_t height)
void Graphics_drawStringCentered (const Graphics_Context *context, int8_t *string, int32_t length, int32_t x, int32_t y, bool opaque)
uint8_t Graphics_getStringHeight (const Graphics_Context *context)
uint8_t Graphics_getStringMaxWidth (const Graphics_Context *context)
uint8_t Graphics_getStringBaseline (const Graphics_Context *context)
uint32_t Graphics_translateColorOnDisplay (const Graphics_Display *display, uint32_t value)
void Graphics_drawHorizontalLineOnDisplay (const Graphics_Display *display, uint16_t x1, uint16_t x2, uint16_t y, uint32_t value)
void Graphics_drawVerticalLineOnDisplay (const Graphics_Display *display, uint16_t x, uint16_t y1, uint16_t y2, uint16_t value)
void Graphics_fillRectangleOnDisplay (const Graphics_Display *display, const Graphics_Rectangle *rect, uint16_t value)
void Graphics_flushOnDisplay (const Graphics_Display *display)
void Graphics_drawPixel (const Graphics_Context *context, uint16_t x, uint16_t y)
void Graphics_clearDisplay (const Graphics_Context *context)
uint16_t Graphics_getHeightOfDisplay (const Graphics_Display *display)
void Graphics_flushBuffer (const Graphics_Context *context)
uint16_t Graphics_getWidthOfDisplay (const Graphics_Display *display)
bool Graphics_isPointWithinRectangle (const Graphics_Rectangle *rect, uint16_t x, uint16_t y)
void Graphics_drawPixelOnDisplay (const Graphics_Display *display, uint16_t x, uint16_t y, uint16_t value)
void Graphics_clearDisplayOnDisplay (const Graphics_Display *display, uint16_t value)
void Graphics_drawMultiplePixelsOnDisplay (const Graphics_Display *display, uint16_t x, uint16_t y, uint16_t x0, uint16_t count, uint16_t bPP, const uint8_t *data, const uint32_t *pucPalette)
void Graphics_initOffscreen1BppImage (Graphics_Display *display, uint8_t *image, int32_t width, int32_t height)
void Graphics_initOffscreen4BppImage (Graphics_Display *display, uint8_t *image, int32_t width, int32_t height)
void Graphics_setOffscreen4BppPalette (Graphics_Display *display, uint32_t *ppalette, uint32_t offset, uint32_t count)
void Graphics_initOffscreen8BppImage (Graphics_Display *display, uint8_t *image, int32_t width, int32_t height)
void Graphics_setOffscreen8BppPalette (Graphics_Display *display, uint32_t *ppalette, uint32_t offset, uint32_t count)
Variables
const Graphics_Font g_sFontCm12
const Graphics_Font g_sFontCm12b
const Graphics_Font g_sFontCm12i
const Graphics_Font g_sFontCm14
const Graphics_Font g_sFontCm14b
const Graphics_Font g_sFontCm14i
const Graphics_Font g_sFontCm16
const Graphics_Font g_sFontCm16b
const Graphics_Font g_sFontCm16i
const Graphics_Font g_sFontCm18
const Graphics_Font g_sFontCm18b
const Graphics_Font g_sFontCm18i
const Graphics_Font g_sFontCm20
const Graphics_Font g_sFontCm20b
const Graphics_Font g_sFontCm20i
const Graphics_Font g_sFontCm22
const Graphics_Font g_sFontCm22b
const Graphics_Font g_sFontCm22i
const Graphics_Font g_sFontCm24
const Graphics_Font g_sFontCm24b
const Graphics_Font g_sFontCm24i
const Graphics_Font g_sFontCm26
const Graphics_Font g_sFontCm26b
const Graphics_Font g_sFontCm26i
const Graphics_Font g_sFontCm28
const Graphics_Font g_sFontCm28b
const Graphics_Font g_sFontCm28i
const Graphics_Font g_sFontCm30
const Graphics_Font g_sFontCm30b
const Graphics_Font g_sFontCm30i
const Graphics_Font g_sFontCm32
const Graphics_Font g_sFontCm32b
const Graphics_Font g_sFontCm32i
const Graphics_Font g_sFontCm34
const Graphics_Font g_sFontCm34b
const Graphics_Font g_sFontCm34i
const Graphics_Font g_sFontCm36
const Graphics_Font g_sFontCm36b
const Graphics_Font g_sFontCm36i
const Graphics_Font g_sFontCm38
const Graphics_Font g_sFontCm38b
const Graphics_Font g_sFontCm38i
const Graphics_Font g_sFontCm40
const Graphics_Font g_sFontCm40b
const Graphics_Font g_sFontCm40i
const Graphics_Font g_sFontCm42
const Graphics_Font g_sFontCm42b
const Graphics_Font g_sFontCm42i
const Graphics_Font g_sFontCm44
const Graphics_Font g_sFontCm44b
const Graphics_Font g_sFontCm44i
const Graphics_Font g_sFontCm46
const Graphics_Font g_sFontCm46b
const Graphics_Font g_sFontCm46i
const Graphics_Font g_sFontCm48
const Graphics_Font g_sFontCm48b
const Graphics_Font g_sFontCm48i
const Graphics_Font g_sFontCmsc12
const Graphics_Font g_sFontCmsc14
const Graphics_Font g_sFontCmsc16
const Graphics_Font g_sFontCmsc18
const Graphics_Font g_sFontCmsc20
const Graphics_Font g_sFontCmsc22
const Graphics_Font g_sFontCmsc24
const Graphics_Font g_sFontCmsc26
const Graphics_Font g_sFontCmsc28
const Graphics_Font g_sFontCmsc30
const Graphics_Font g_sFontCmsc32
const Graphics_Font g_sFontCmsc34
const Graphics_Font g_sFontCmsc36
const Graphics_Font g_sFontCmsc38
const Graphics_Font g_sFontCmsc40
const Graphics_Font g_sFontCmsc42
const Graphics_Font g_sFontCmsc44
const Graphics_Font g_sFontCmsc46
const Graphics_Font g_sFontCmsc48
const Graphics_Font g_sFontCmss12
const Graphics_Font g_sFontCmss12b
const Graphics_Font g_sFontCmss12i
const Graphics_Font g_sFontCmss14
const Graphics_Font g_sFontCmss14b
const Graphics_Font g_sFontCmss14i
const Graphics_Font g_sFontCmss16
const Graphics_Font g_sFontCmss16b
const Graphics_Font g_sFontCmss16i
const Graphics_Font g_sFontCmss18
const Graphics_Font g_sFontCmss18b
const Graphics_Font g_sFontCmss18i
const Graphics_Font g_sFontCmss20
const Graphics_Font g_sFontCmss20b
const Graphics_Font g_sFontCmss20i
const Graphics_Font g_sFontCmss22
const Graphics_Font g_sFontCmss22b
const Graphics_Font g_sFontCmss22i
const Graphics_Font g_sFontCmss24
const Graphics_Font g_sFontCmss24b
const Graphics_Font g_sFontCmss24i
const Graphics_Font g_sFontCmss26
const Graphics_Font g_sFontCmss26b
const Graphics_Font g_sFontCmss26i
const Graphics_Font g_sFontCmss28
const Graphics_Font g_sFontCmss28b
const Graphics_Font g_sFontCmss28i
const Graphics_Font g_sFontCmss30
const Graphics_Font g_sFontCmss30b
const Graphics_Font g_sFontCmss30i
const Graphics_Font g_sFontCmss32
const Graphics_Font g_sFontCmss32b
const Graphics_Font g_sFontCmss32i
const Graphics_Font g_sFontCmss34
const Graphics_Font g_sFontCmss34b
const Graphics_Font g_sFontCmss34i
const Graphics_Font g_sFontCmss36
const Graphics_Font g_sFontCmss36b
const Graphics_Font g_sFontCmss36i
const Graphics_Font g_sFontCmss38
const Graphics_Font g_sFontCmss38b
const Graphics_Font g_sFontCmss38i
const Graphics_Font g_sFontCmss40
const Graphics_Font g_sFontCmss40b
const Graphics_Font g_sFontCmss40i
const Graphics_Font g_sFontCmss42
const Graphics_Font g_sFontCmss42b
const Graphics_Font g_sFontCmss42i
const Graphics_Font g_sFontCmss44
const Graphics_Font g_sFontCmss44b
const Graphics_Font g_sFontCmss44i
const Graphics_Font g_sFontCmss46
const Graphics_Font g_sFontCmss46b
const Graphics_Font g_sFontCmss46i
const Graphics_Font g_sFontCmss48
const Graphics_Font g_sFontCmss48b
const Graphics_Font g_sFontCmss48i
const Graphics_Font g_sFontCmtt12
const Graphics_Font g_sFontCmtt14
const Graphics_Font g_sFontCmtt16
const Graphics_Font g_sFontCmtt18
const Graphics_Font g_sFontCmtt20
const Graphics_Font g_sFontCmtt22
const Graphics_Font g_sFontCmtt24
const Graphics_Font g_sFontCmtt26
const Graphics_Font g_sFontCmtt28
const Graphics_Font g_sFontCmtt30
const Graphics_Font g_sFontCmtt32
const Graphics_Font g_sFontCmtt34
const Graphics_Font g_sFontCmtt36
const Graphics_Font g_sFontCmtt38
const Graphics_Font g_sFontCmtt40
const Graphics_Font g_sFontCmtt42
const Graphics_Font g_sFontCmtt44
const Graphics_Font g_sFontCmtt46
const Graphics_Font g_sFontCmtt48
const Graphics_Font g_sFontFixed6x8
Detailed Description
Macro Definition Documentation
min
#define min (a, b) (((a) < (b)) ? (a) : (b))
Referenced by Graphics_getRectangleIntersection().
max
#define max (a, b) (((a) < (b)) ? (b) : (a))
Referenced by Graphics_getRectangleIntersection().
ClrAliceBlue
#define ClrAliceBlue GRAPHICS_COLOR_ALICE_BLUE
ClrAntiqueWhite
#define ClrAntiqueWhite GRAPHICS_COLOR_ANTIQUE_WHITE
ClrAqua
#define ClrAqua GRAPHICS_COLOR_AQUA
ClrAquamarine
#define ClrAquamarine GRAPHICS_COLOR_AQUAMARINE
ClrAzure
#define ClrAzure GRAPHICS_COLOR_AZURE
ClrBeige
#define ClrBeige GRAPHICS_COLOR_BEIGE
ClrBisque
#define ClrBisque GRAPHICS_COLOR_BISQUE
ClrBlack [1/2]
#define ClrBlack GRAPHICS_COLOR_BLACK
ClrBlack [2/2]
#define ClrBlack GRAPHICS_COLOR_BLACK
ClrBlanchedAlmond
#define ClrBlanchedAlmond GRAPHICS_COLOR_BLANCHED_ALMOND
ClrBlue
#define ClrBlue GRAPHICS_COLOR_BLUE
ClrBlueViolet
#define ClrBlueViolet GRAPHICS_COLOR_BLUE_VIOLET
ClrBrown
#define ClrBrown GRAPHICS_COLOR_BROWN
ClrBurlyWood
#define ClrBurlyWood GRAPHICS_COLOR_BURLY_WOOD
ClrCadetBlue
#define ClrCadetBlue GRAPHICS_COLOR_CADET_BLUE
ClrChartreuse
#define ClrChartreuse GRAPHICS_COLOR_CHARTREUSE
ClrChocolate
#define ClrChocolate GRAPHICS_COLOR_CHOCOLATE
ClrCoral
#define ClrCoral GRAPHICS_COLOR_CORAL
ClrCornflowerBlue
#define ClrCornflowerBlue GRAPHICS_COLOR_CORNFLOWER_BLUE
ClrCornsilk
#define ClrCornsilk GRAPHICS_COLOR_CORNSILK
ClrCrimson
#define ClrCrimson GRAPHICS_COLOR_CRIMSON
ClrCyan
#define ClrCyan GRAPHICS_COLOR_CYAN
ClrDarkBlue
#define ClrDarkBlue GRAPHICS_COLOR_DARK_BLUE
ClrDarkCyan
#define ClrDarkCyan GRAPHICS_COLOR_DARK_CYAN
ClrDarkGoldenrod
#define ClrDarkGoldenrod GRAPHICS_COLOR_DARK_GOLDENROD
ClrDarkGray
#define ClrDarkGray GRAPHICS_COLOR_DARK_GRAY
ClrDarkGreen
#define ClrDarkGreen GRAPHICS_COLOR_DARK_GREEN
ClrDarkKhaki
#define ClrDarkKhaki GRAPHICS_COLOR_DARK_KHAKI
ClrDarkMagenta
#define ClrDarkMagenta GRAPHICS_COLOR_DARK_MAGENTA
ClrDarkOliveGreen
#define ClrDarkOliveGreen GRAPHICS_COLOR_DARK_OLIVE_GREEN
ClrDarkOrange
#define ClrDarkOrange GRAPHICS_COLOR_DARK_ORANGE
ClrDarkOrchid
#define ClrDarkOrchid GRAPHICS_COLOR_DARK_ORCHID
ClrDarkRed
#define ClrDarkRed GRAPHICS_COLOR_DARK_RED
ClrDarkSalmon
#define ClrDarkSalmon GRAPHICS_COLOR_DARK_SALMON
ClrDarkSeaGreen
#define ClrDarkSeaGreen GRAPHICS_COLOR_DARK_SEA_GREEN
ClrDarkSlateBlue
#define ClrDarkSlateBlue GRAPHICS_COLOR_DARK_SLATE_BLUE
ClrDarkSlateGray
#define ClrDarkSlateGray GRAPHICS_COLOR_DARK_SLATE_GRAY
ClrDarkTurquoise
#define ClrDarkTurquoise GRAPHICS_COLOR_DARK_TURQUOISE
ClrDarkViolet
#define ClrDarkViolet GRAPHICS_COLOR_DARK_VIOLET
ClrDeepPink
#define ClrDeepPink GRAPHICS_COLOR_DEEP_PINK
ClrDeepSkyBlue
#define ClrDeepSkyBlue GRAPHICS_COLOR_DEEP_SKY_BLUE
ClrDimGray
#define ClrDimGray GRAPHICS_COLOR_DIM_GRAY
ClrDodgerBlue
#define ClrDodgerBlue GRAPHICS_COLOR_DODGER_BLUE
ClrFireBrick
#define ClrFireBrick GRAPHICS_COLOR_FIRE_BRICK
ClrFloralWhite
#define ClrFloralWhite GRAPHICS_COLOR_FLORAL_WHITE
ClrForestGreen
#define ClrForestGreen GRAPHICS_COLOR_FOREST_GREEN
ClrFuchsia
#define ClrFuchsia GRAPHICS_COLOR_FUCHSIA
ClrGainsboro
#define ClrGainsboro GRAPHICS_COLOR_GAINSBORO
ClrGhostWhite
#define ClrGhostWhite GRAPHICS_COLOR_GHOST_WHITE
ClrGold
#define ClrGold GRAPHICS_COLOR_GOLD
ClrGoldenrod
#define ClrGoldenrod GRAPHICS_COLOR_GOLDENRON
ClrGray
#define ClrGray GRAPHICS_COLOR_GRAY
ClrGreen
#define ClrGreen GRAPHICS_COLOR_GREEN
ClrGreenYellow
#define ClrGreenYellow GRAPHICS_COLOR_GREEN_YELLOW
ClrHoneydew
#define ClrHoneydew GRAPHICS_COLOR_HONEYDEW
ClrHotPink
#define ClrHotPink GRAPHICS_COLOR_HOT_PINK
ClrIndianRed
#define ClrIndianRed GRAPHICS_COLOR_INDIAN_RED
ClrIndigo
#define ClrIndigo GRAPHICS_COLOR_INDIGO
ClrIvory
#define ClrIvory GRAPHICS_COLOR_IVORY
ClrKhaki
#define ClrKhaki GRAPHICS_COLOR_KHAKI
ClrLavender
#define ClrLavender GRAPHICS_COLOR_LAVENDER
ClrLavenderBlush
#define ClrLavenderBlush GRAPHICS_COLOR_LAVENDER_BLUSH
ClrLawnGreen
#define ClrLawnGreen GRAPHICS_COLOR_LAWN_GREEN
ClrLemonChiffon
#define ClrLemonChiffon GRAPHICS_COLOR_LEMON_CHIFFON
ClrLightBlue
#define ClrLightBlue GRAPHICS_COLOR_LIGHT_BLUE
ClrLightCoral
#define ClrLightCoral GRAPHICS_COLOR_LIGHT_CORAL
ClrLightCyan
#define ClrLightCyan GRAPHICS_COLOR_LIGHT_CYAN
ClrLightGoldenrodYellow
#define ClrLightGoldenrodYellow GRAPHICS_COLOR_LIGHT_GOLDENRON_YELLOW
ClrLightGreen
#define ClrLightGreen GRAPHICS_COLOR_LIGHT_GREEN
ClrLightGrey
#define ClrLightGrey GRAPHICS_COLOR_LIGHT_GRAY
ClrLightPink
#define ClrLightPink GRAPHICS_COLOR_LIGHT_PINK
ClrLightSalmon
#define ClrLightSalmon GRAPHICS_COLOR_LIGHT_SALMON
ClrLightSeaGreen
#define ClrLightSeaGreen GRAPHICS_COLOR_LIGHT_SEA_GREEN
ClrLightSkyBlue
#define ClrLightSkyBlue GRAPHICS_COLOR_LIGHT_SKY_BLUE
ClrLightSlateGray
#define ClrLightSlateGray GRAPHICS_COLOR_LIGHT_SLATE_GRAY
ClrLightSteelBlue
#define ClrLightSteelBlue GRAPHICS_COLOR_LIGHT_STEEL_BLUE
ClrLightYellow
#define ClrLightYellow GRAPHICS_COLOR_LIGHT_YELLOW
ClrLime
#define ClrLime GRAPHICS_COLOR_LIME
ClrLimeGreen
#define ClrLimeGreen GRAPHICS_COLOR_LIME_GREEN
ClrLinen
#define ClrLinen GRAPHICS_COLOR_LINEN
ClrMagenta
#define ClrMagenta GRAPHICS_COLOR_MAGENTA
ClrMaroon
#define ClrMaroon GRAPHICS_COLOR_MAROON
ClrMediumAquamarine
#define ClrMediumAquamarine GRAPHICS_COLOR_MEDIUM_AQUAMARINE
ClrMediumBlue
#define ClrMediumBlue GRAPHICS_COLOR_MEDIUM_BLUE
ClrMediumOrchid
#define ClrMediumOrchid GRAPHICS_COLOR_MEDIUM_ORCHID
ClrMediumPurple
#define ClrMediumPurple GRAPHICS_COLOR_MEDIUM_PURPLE
ClrMediumSeaGreen
#define ClrMediumSeaGreen GRAPHICS_COLOR_MEDIUM_SEA_GREEN
ClrMediumSlateBlue
#define ClrMediumSlateBlue GRAPHICS_COLOR_MEDIUM_SLATE_BLUE
ClrMediumSpringGreen
#define ClrMediumSpringGreen GRAPHICS_COLOR_MEDIUM_SPRING_GREEN
ClrMediumTurquoise
#define ClrMediumTurquoise GRAPHICS_COLOR_MEDIUM_TURQUOISE
ClrMediumVioletRed
#define ClrMediumVioletRed GRAPHICS_COLOR_MEDIUM_VIOLET_RED
ClrMidnightBlue
#define ClrMidnightBlue GRAPHICS_COLOR_MIGNIGHT_BLUE
ClrMintCream
#define ClrMintCream GRAPHICS_COLOR_MINT_CREAM
ClrMistyRose
#define ClrMistyRose GRAPHICS_COLOR_MISTY_ROSE
ClrMoccasin
#define ClrMoccasin GRAPHICS_COLOR_MOCCASIN
ClrNavajoWhite
#define ClrNavajoWhite GRAPHICS_COLOR_NAVAJO_WHITE
ClrNavy
#define ClrNavy GRAPHICS_COLOR_NAVY
ClrOldLace
#define ClrOldLace GRAPHICS_COLOR_OLD_LACE
ClrOlive
#define ClrOlive GRAPHICS_COLOR_OLIVE
ClrOliveDrab
#define ClrOliveDrab GRAPHICS_COLOR_OLIVE_DRAB
ClrOrange
#define ClrOrange GRAPHICS_COLOR_ORANGE
ClrOrangeRed
#define ClrOrangeRed GRAPHICS_COLOR_ORANGE_RED
ClrOrchid
#define ClrOrchid GRAPHICS_COLOR_ORCHID
ClrPaleGoldenrod
#define ClrPaleGoldenrod GRAPHICS_COLOR_PALE_GOLDENRON
ClrPaleGreen
#define ClrPaleGreen GRAPHICS_COLOR_PALE_GREEN
ClrPaleTurquoise
#define ClrPaleTurquoise GRAPHICS_COLOR_PALE_TURQUOISE
ClrPaleVioletRed
#define ClrPaleVioletRed GRAPHICS_COLOR_PALE_VIOLET_RED
ClrPapayaWhip
#define ClrPapayaWhip GRAPHICS_COLOR_PAPAYA_WHIP
ClrPeachPuff
#define ClrPeachPuff GRAPHICS_COLOR_PEACH_PUFF
ClrPeru
#define ClrPeru GRAPHICS_COLOR_PERU
ClrPink
#define ClrPink GRAPHICS_COLOR_PINK
ClrPlum
#define ClrPlum GRAPHICS_COLOR_PLUM
ClrPowderBlue
#define ClrPowderBlue GRAPHICS_COLOR_POWDER_BLUE
ClrPurple
#define ClrPurple GRAPHICS_COLOR_PURPLE
ClrRed
#define ClrRed GRAPHICS_COLOR_RED
ClrRosyBrown
#define ClrRosyBrown GRAPHICS_COLOR_ROSY_BROWN
ClrRoyalBlue
#define ClrRoyalBlue GRAPHICS_COLOR_ROYAL_BLUE
ClrSaddleBrown
#define ClrSaddleBrown GRAPHICS_COLOR_SADDLE_BROWN
ClrSalmon
#define ClrSalmon GRAPHICS_COLOR_SALMON
ClrSandyBrown
#define ClrSandyBrown GRAPHICS_COLOR_SANDY_BROWN
ClrSeaGreen
#define ClrSeaGreen GRAPHICS_COLOR_SEA_GREEN
ClrSeashell
#define ClrSeashell GRAPHICS_COLOR_SEASHELL
ClrSienna
#define ClrSienna GRAPHICS_COLOR_SIENNA
ClrSilver
#define ClrSilver GRAPHICS_COLOR_SILVER
ClrSkyBlue
#define ClrSkyBlue GRAPHICS_COLOR_SKY_BLUE
ClrSlateBlue
#define ClrSlateBlue GRAPHICS_COLOR_SLATE_BLUE
ClrSlateGray
#define ClrSlateGray GRAPHICS_COLOR_SLATE_GRAY
ClrSnow
#define ClrSnow GRAPHICS_COLOR_SNOW
ClrSpringGreen
#define ClrSpringGreen GRAPHICS_COLOR_SPRING_GREEN
ClrSteelBlue
#define ClrSteelBlue GRAPHICS_COLOR_STEEL_BLUE
ClrTan
#define ClrTan GRAPHICS_COLOR_TAN
ClrTeal
#define ClrTeal GRAPHICS_COLOR_TEAL
ClrThistle
#define ClrThistle GRAPHICS_COLOR_THISTLE
ClrTomato
#define ClrTomato GRAPHICS_COLOR_TOMATO
ClrTurquoise
#define ClrTurquoise GRAPHICS_COLOR_TURQUOISE
ClrViolet
#define ClrViolet GRAPHICS_COLOR_VIOLET
ClrWheat
#define ClrWheat GRAPHICS_COLOR_WHEAT
ClrWhite
#define ClrWhite GRAPHICS_COLOR_WHITE
ClrWhiteSmoke
#define ClrWhiteSmoke GRAPHICS_COLOR_WHITE_SMOKE
ClrYellow
#define ClrYellow GRAPHICS_COLOR_YELLOW
ClrYellowGreen
#define ClrYellowGreen GRAPHICS_COLOR_YELLOW_GREEN
FONT_FMT_UNCOMPRESSED
#define FONT_FMT_UNCOMPRESSED GRAPHICS_FONT_FMT_UNCOMPRESSED
FONT_FMT_PIXEL_RLE
#define FONT_FMT_PIXEL_RLE GRAPHICS_FONT_FMT_PIXEL_RLE
FONT_EX_MARKER
#define FONT_EX_MARKER GRAPHICS_FONT_EX_MARKER
FONT_FMT_EX_UNCOMPRESSED
#define FONT_FMT_EX_UNCOMPRESSED GRAPHICS_FONT_FMT_EX_UNCOMPRESSED
FONT_FMT_EX_PIXEL_RLE
#define FONT_FMT_EX_PIXEL_RLE GRAPHICS_FONT_FMT_EX_PIXEL_RLE
AUTO_STRING_LENGTH
#define AUTO_STRING_LENGTH GRAPHICS_AUTO_STRING_LENGTH
Referenced by Graphics_drawCheckBox(), and Graphics_drawRadioButton().
OPAQUE_TEXT
#define OPAQUE_TEXT GRAPHICS_OPAQUE_TEXT
TRANSPARENT_TEXT
#define TRANSPARENT_TEXT GRAPHICS_TRANSPARENT_TEXT
Referenced by Graphics_drawCheckBox(), and Graphics_drawRadioButton().
IMAGE_FMT_1BPP_UNCOMP
#define IMAGE_FMT_1BPP_UNCOMP GRAPHICS_IMAGE_FMT_1BPP_UNCOMP
IMAGE_FMT_2BPP_UNCOMP [1/2]
#define IMAGE_FMT_2BPP_UNCOMP GRAPHICS_IMAGE_FMT_2BPP_UNCOMP
IMAGE_FMT_2BPP_UNCOMP [2/2]
#define IMAGE_FMT_2BPP_UNCOMP GRAPHICS_IMAGE_FMT_2BPP_UNCOMP
IMAGE_FMT_4BPP_UNCOMP
#define IMAGE_FMT_4BPP_UNCOMP GRAPHICS_IMAGE_FMT_4BPP_UNCOMP
IMAGE_FMT_8BPP_UNCOMP
#define IMAGE_FMT_8BPP_UNCOMP GRAPHICS_IMAGE_FMT_8BPP_UNCOMP
IMAGE_FMT_1BPP_COMP_RLE4
#define IMAGE_FMT_1BPP_COMP_RLE4 GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE4
IMAGE_FMT_4BPP_COMP_RLE4
#define IMAGE_FMT_4BPP_COMP_RLE4 GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE4
IMAGE_FMT_1BPP_COMP_RLE7
#define IMAGE_FMT_1BPP_COMP_RLE7 GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE7
IMAGE_FMT_1BPP_COMP_RLE8
#define IMAGE_FMT_1BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE8
IMAGE_FMT_2BPP_COMP_RLE8
#define IMAGE_FMT_2BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE8
IMAGE_FMT_4BPP_COMP_RLE8
#define IMAGE_FMT_4BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE8
IMAGE_FMT_8BPP_COMP_RLE8
#define IMAGE_FMT_8BPP_COMP_RLE8 GRAPHICS_IMAGE_FMT_8BPP_COMP_RLE8
IMAGE_FMT_8BPP_COMP_RLEBLEND
#define IMAGE_FMT_8BPP_COMP_RLEBLEND GRAPHICS_IMAGE_FMT_8BPP_COMP_RLEBLEND
tFontEx
#define tFontEx Graphics_FontEx
tFont
#define tFont Graphics_Font
tDisplay
#define tDisplay Graphics_Display
tRectangle
#define tRectangle Graphics_Rectangle
tImage
#define tImage Graphics_Image
tContext
#define tContext Graphics_Context
sXMax
#define sXMax xMax
sXMin
#define sXMin xMin
sYMax
#define sYMax yMax
sYMin
#define sYMin yMin
GrCircleDraw
#define GrCircleDraw Graphics_drawCircle
GrCircleFill
#define GrCircleFill Graphics_fillCircle
GrContextClipRegionSet
#define GrContextClipRegionSet Graphics_setClipRegion
GrContextInit
#define GrContextInit Graphics_initContext
GrImageDraw
#define GrImageDraw Graphics_drawImage
GrLineDraw
#define GrLineDraw Graphics_drawLine
GrLineDrawH
#define GrLineDrawH Graphics_drawLineH
GrLineDrawV
#define GrLineDrawV Graphics_drawLineV
GrRectDraw
#define GrRectDraw Graphics_drawRectangle
GrRectFill
#define GrRectFill Graphics_fillRectangle
GrStringDraw
#define GrStringDraw Graphics_drawString
GrStringWidthGet
#define GrStringWidthGet Graphics_getStringWidth
GrRectOverlapCheck
#define GrRectOverlapCheck Graphics_isOverlappingRectangle
GrRectIntersectGet
#define GrRectIntersectGet Graphics_getRectangleIntersection
GrContextBackgroundSet
#define GrContextBackgroundSet Graphics_setBackgroundColor
GrContextBackgroundSetTranslated
#define GrContextBackgroundSetTranslated Graphics_setBackgroundColorTranslated
GrContextDpyWidthGet
#define GrContextDpyWidthGet Graphics_getDisplayWidth
GrContextDpyHeightGet
#define GrContextDpyHeightGet Graphics_getDisplayHeight
GrContextFontSet
#define GrContextFontSet Graphics_setFont
GrContextForegroundSet
#define GrContextForegroundSet Graphics_setForegroundColor
GrContextForegroundSetTranslated
#define GrContextForegroundSetTranslated Graphics_setForegroundColorTranslated
GrFlush
#define GrFlush Graphics_flushBuffer
GrClearDisplay
#define GrClearDisplay Graphics_clearDisplay
GrFontBaselineGet
#define GrFontBaselineGet Graphics_getFontBaseline
GrFontHeightGet
#define GrFontHeightGet Graphics_getFontHeight
GrFontMaxWidthGet
#define GrFontMaxWidthGet Graphics_getFontMaxWidth
GrImageColorsGet
#define GrImageColorsGet Graphics_getImageColors
GrImageHeightGet
#define GrImageHeightGet Graphics_getImageHeight
GrImageWidthGet
#define GrImageWidthGet Graphics_getImageWidth
GrOffScreen1BPPSize
#define GrOffScreen1BPPSize Graphics_getOffscreen1BppImageSize
GrOffScreen4BPPSize
#define GrOffScreen4BPPSize Graphics_getOffscreen4BppImageSize
GrOffScreen8BPPSize
#define GrOffScreen8BPPSize Graphics_getOffscreen8BppImageSize
GrPixelDraw
#define GrPixelDraw Graphics_drawPixel
GrStringBaselineGet
#define GrStringBaselineGet Graphics_getStringBaseline
GrStringDrawCentered
#define GrStringDrawCentered Graphics_drawStringCentered
GrStringHeightGet
#define GrStringHeightGet Graphics_getStringHeight
GrStringMaxWidthGet
#define GrStringMaxWidthGet Graphics_getStringMaxWidth
DpyColorTranslate
#define DpyColorTranslate Graphics_translateColorOnDisplay
DpyFlush
#define DpyFlush Graphics_flushOnDisplay
DpyClearDisplay
#define DpyClearDisplay Graphics_clearDisplayOnDisplay
DpyHeightGet
#define DpyHeightGet Graphics_getHeightOfDisplay
DpyLineDrawH
#define DpyLineDrawH Graphics_drawHorizontalLineOnDisplay
DpyLineDrawV
#define DpyLineDrawV Graphics_drawVerticalLineOnDisplay
DpyPixelDraw
#define DpyPixelDraw Graphics_drawPixelOnDisplay
DpyPixelDrawMultiple
#define DpyPixelDrawMultiple Graphics_drawMultiplePixelsOnDisplay
DpyRectFill
#define DpyRectFill Graphics_fillRectangleOnDisplay
DpyWidthGet
#define DpyWidthGet Graphics_getWidthOfDisplay
GrRectContainsPoint
#define GrRectContainsPoint Graphics_isPointWithinRectangle
GRAPHICS_FONT_FMT_UNCOMPRESSED
#define GRAPHICS_FONT_FMT_UNCOMPRESSED 0x00
Indicates that the font data is stored in an uncompressed format.
Referenced by Graphics_drawString().
GRAPHICS_FONT_FMT_PIXEL_RLE
#define GRAPHICS_FONT_FMT_PIXEL_RLE 0x01
Indicates that the font data is stored using a pixel-based RLE format.
GRAPHICS_FONT_EX_MARKER
#define GRAPHICS_FONT_EX_MARKER 0x80
A marker used in the format field of a font to indicates that the font data is stored using the new tFontEx structure.
Referenced by Graphics_drawString(), and Graphics_getStringWidth().
GRAPHICS_FONT_FMT_EX_UNCOMPRESSED
#define GRAPHICS_FONT_FMT_EX_UNCOMPRESSED
Value:
(FONT_FMT_UNCOMPRESSED | \
                                             FONT_EX_MARKER)
Indicates that the font data is stored in an uncompressed format and uses the tFontEx structure format.
GRAPHICS_FONT_FMT_EX_PIXEL_RLE
#define GRAPHICS_FONT_FMT_EX_PIXEL_RLE
Value:
(FONT_FMT_PIXEL_RLE | \
                                             FONT_EX_MARKER)
Indicates that the font data is stored using a pixel-based RLE format and uses the tFontEx structure format.
GRAPHICS_AUTO_STRING_LENGTH
#define GRAPHICS_AUTO_STRING_LENGTH -1
Value to automatically draw the entire length of the string (subject to clipping)
GRAPHICS_OPAQUE_TEXT
#define GRAPHICS_OPAQUE_TEXT 1
Value to draw text opaque The text foreground and background are drawn together
GRAPHICS_TRANSPARENT_TEXT
#define GRAPHICS_TRANSPARENT_TEXT 0
Value to draw text transparently The text only (no background) is drawn
GRAPHICS_IMAGE_FMT_1BPP_UNCOMP
#define GRAPHICS_IMAGE_FMT_1BPP_UNCOMP 0x01
Indicates that the image data is not compressed and represents each pixel with a single bit.
GRAPHICS_IMAGE_FMT_2BPP_UNCOMP
#define GRAPHICS_IMAGE_FMT_2BPP_UNCOMP 0x02
Indicates that the image data is not compressed and represents each pixel with two bits.
GRAPHICS_IMAGE_FMT_4BPP_UNCOMP
#define GRAPHICS_IMAGE_FMT_4BPP_UNCOMP 0x04
Indicates that the image data is not compressed and represents each pixel with four bits.
GRAPHICS_IMAGE_FMT_8BPP_UNCOMP
#define GRAPHICS_IMAGE_FMT_8BPP_UNCOMP 0x08
Indicates that the image data is not compressed and represents each pixel with eight bits.
GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE4
#define GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE4 0x41
Indicates that the image data is compressed with 4 bit Run Length Encoding and represents each pixel with a single bit.
GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE4
#define GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE4 0x42
Indicates that the image data is compressed with 4 bit Run Length Encoding and represents each pixel with two bits.
GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE4
#define GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE4 0x44
Indicates that the image data is compressed with 4 bit Run Length Encoding and represents each pixel with four bits.
GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE7
#define GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE7 0x71
Indicates that the image data is compressed with 7 bit Run Length Encoding and represents each pixel with a single bit.
GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE8
#define GRAPHICS_IMAGE_FMT_1BPP_COMP_RLE8 0x81
Indicates that the image data is compressed with 8 bit Run Length Encoding and represents each pixel with a single bit.
GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE8
#define GRAPHICS_IMAGE_FMT_2BPP_COMP_RLE8 0x82
Indicates that the image data is compressed with 8 bit Run Length Encoding and represents each pixel with two bits.
GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE8
#define GRAPHICS_IMAGE_FMT_4BPP_COMP_RLE8 0x84
Indicates that the image data is compressed with 8 bit Run Length Encoding and represents each pixel with four bits.
GRAPHICS_IMAGE_FMT_8BPP_COMP_RLE8
#define GRAPHICS_IMAGE_FMT_8BPP_COMP_RLE8 0x88
Indicates that the image data is compressed with 8 bit Run Length Encoding and represents each pixel with eight bits.
GRAPHICS_IMAGE_FMT_8BPP_COMP_RLEBLEND
#define GRAPHICS_IMAGE_FMT_8BPP_COMP_RLEBLEND 0x28
Indicates that the image data is compressed and represents each pixel with info bits.
GRAPHICS_COLOR_ALICE_BLUE
#define GRAPHICS_COLOR_ALICE_BLUE 0x00F0F8FF
GRAPHICS_COLOR_ANTIQUE_WHITE
#define GRAPHICS_COLOR_ANTIQUE_WHITE 0x00FAEBD7
GRAPHICS_COLOR_AQUA
#define GRAPHICS_COLOR_AQUA 0x0000FFFF
GRAPHICS_COLOR_AQUAMARINE
#define GRAPHICS_COLOR_AQUAMARINE 0x007FFFD4
GRAPHICS_COLOR_AZURE
#define GRAPHICS_COLOR_AZURE 0x00F0FFFF
GRAPHICS_COLOR_BEIGE
#define GRAPHICS_COLOR_BEIGE 0x00F5F5DC
GRAPHICS_COLOR_BISQUE
#define GRAPHICS_COLOR_BISQUE 0x00FFE4C4
GRAPHICS_COLOR_BLACK [1/2]
#define GRAPHICS_COLOR_BLACK 0x00000000
GRAPHICS_COLOR_BLACK [2/2]
#define GRAPHICS_COLOR_BLACK 0x00000000
GRAPHICS_COLOR_BLANCHED_ALMOND
#define GRAPHICS_COLOR_BLANCHED_ALMOND 0x00FFEBCD
GRAPHICS_COLOR_BLUE
#define GRAPHICS_COLOR_BLUE 0x000000FF
GRAPHICS_COLOR_BLUE_VIOLET
#define GRAPHICS_COLOR_BLUE_VIOLET 0x008A2BE2
GRAPHICS_COLOR_BROWN
#define GRAPHICS_COLOR_BROWN 0x00A52A2A
GRAPHICS_COLOR_BURLY_WOOD
#define GRAPHICS_COLOR_BURLY_WOOD 0x00DEB887
GRAPHICS_COLOR_CADET_BLUE
#define GRAPHICS_COLOR_CADET_BLUE 0x005F9EA0
GRAPHICS_COLOR_CHARTREUSE
#define GRAPHICS_COLOR_CHARTREUSE 0x007FFF00
GRAPHICS_COLOR_CHOCOLATE
#define GRAPHICS_COLOR_CHOCOLATE 0x00D2691E
GRAPHICS_COLOR_CORAL
#define GRAPHICS_COLOR_CORAL 0x00FF7F50
GRAPHICS_COLOR_CORNFLOWER_BLUE
#define GRAPHICS_COLOR_CORNFLOWER_BLUE 0x006495ED
GRAPHICS_COLOR_CORNSILK
#define GRAPHICS_COLOR_CORNSILK 0x00FFF8DC
GRAPHICS_COLOR_CRIMSON
#define GRAPHICS_COLOR_CRIMSON 0x00DC143C
GRAPHICS_COLOR_CYAN
#define GRAPHICS_COLOR_CYAN 0x0000FFFF
GRAPHICS_COLOR_DARK_BLUE
#define GRAPHICS_COLOR_DARK_BLUE 0x0000008B
GRAPHICS_COLOR_DARK_CYAN
#define GRAPHICS_COLOR_DARK_CYAN 0x00008B8B
GRAPHICS_COLOR_DARK_GOLDENROD
#define GRAPHICS_COLOR_DARK_GOLDENROD 0x00B8860B
GRAPHICS_COLOR_DARK_GRAY
#define GRAPHICS_COLOR_DARK_GRAY 0x00A9A9A9
GRAPHICS_COLOR_DARK_GREEN
#define GRAPHICS_COLOR_DARK_GREEN 0x00006400
GRAPHICS_COLOR_DARK_KHAKI
#define GRAPHICS_COLOR_DARK_KHAKI 0x00BDB76B
GRAPHICS_COLOR_DARK_MAGENTA
#define GRAPHICS_COLOR_DARK_MAGENTA 0x008B008B
GRAPHICS_COLOR_DARK_OLIVE_GREEN
#define GRAPHICS_COLOR_DARK_OLIVE_GREEN 0x00556B2F
GRAPHICS_COLOR_DARK_ORANGE
#define GRAPHICS_COLOR_DARK_ORANGE 0x00FF8C00
GRAPHICS_COLOR_DARK_ORCHID
#define GRAPHICS_COLOR_DARK_ORCHID 0x009932CC
GRAPHICS_COLOR_DARK_RED
#define GRAPHICS_COLOR_DARK_RED 0x008B0000
GRAPHICS_COLOR_DARK_SALMON
#define GRAPHICS_COLOR_DARK_SALMON 0x00E9967A
GRAPHICS_COLOR_DARK_SEA_GREEN
#define GRAPHICS_COLOR_DARK_SEA_GREEN 0x008FBC8F
GRAPHICS_COLOR_DARK_SLATE_BLUE
#define GRAPHICS_COLOR_DARK_SLATE_BLUE 0x00483D8B
GRAPHICS_COLOR_DARK_SLATE_GRAY
#define GRAPHICS_COLOR_DARK_SLATE_GRAY 0x002F4F4F
GRAPHICS_COLOR_DARK_TURQUOISE
#define GRAPHICS_COLOR_DARK_TURQUOISE 0x0000CED1
GRAPHICS_COLOR_DARK_VIOLET
#define GRAPHICS_COLOR_DARK_VIOLET 0x009400D3
GRAPHICS_COLOR_DEEP_PINK
#define GRAPHICS_COLOR_DEEP_PINK 0x00FF1493
GRAPHICS_COLOR_DEEP_SKY_BLUE
#define GRAPHICS_COLOR_DEEP_SKY_BLUE 0x0000BFFF
GRAPHICS_COLOR_DIM_GRAY
#define GRAPHICS_COLOR_DIM_GRAY 0x00696969
GRAPHICS_COLOR_DODGER_BLUE
#define GRAPHICS_COLOR_DODGER_BLUE 0x001E90FF
GRAPHICS_COLOR_FIRE_BRICK
#define GRAPHICS_COLOR_FIRE_BRICK 0x00B22222
GRAPHICS_COLOR_FLORAL_WHITE
#define GRAPHICS_COLOR_FLORAL_WHITE 0x00FFFAF0
GRAPHICS_COLOR_FOREST_GREEN
#define GRAPHICS_COLOR_FOREST_GREEN 0x00228B22
GRAPHICS_COLOR_FUCHSIA
#define GRAPHICS_COLOR_FUCHSIA 0x00FF00FF
GRAPHICS_COLOR_GAINSBORO
#define GRAPHICS_COLOR_GAINSBORO 0x00DCDCDC
GRAPHICS_COLOR_GHOST_WHITE
#define GRAPHICS_COLOR_GHOST_WHITE 0x00F8F8FF
GRAPHICS_COLOR_GOLD
#define GRAPHICS_COLOR_GOLD 0x00FFD700
GRAPHICS_COLOR_GOLDENRON
#define GRAPHICS_COLOR_GOLDENRON 0x00DAA520
GRAPHICS_COLOR_GRAY
#define GRAPHICS_COLOR_GRAY 0x00808080
GRAPHICS_COLOR_GREEN
#define GRAPHICS_COLOR_GREEN 0x00008000
GRAPHICS_COLOR_GREEN_YELLOW
#define GRAPHICS_COLOR_GREEN_YELLOW 0x00ADFF2F
GRAPHICS_COLOR_HONEYDEW
#define GRAPHICS_COLOR_HONEYDEW 0x00F0FFF0
GRAPHICS_COLOR_HOT_PINK
#define GRAPHICS_COLOR_HOT_PINK 0x00FF69B4
GRAPHICS_COLOR_INDIAN_RED
#define GRAPHICS_COLOR_INDIAN_RED 0x00CD5C5C
GRAPHICS_COLOR_INDIGO
#define GRAPHICS_COLOR_INDIGO 0x004B0082
GRAPHICS_COLOR_IVORY
#define GRAPHICS_COLOR_IVORY 0x00FFFFF0
GRAPHICS_COLOR_KHAKI
#define GRAPHICS_COLOR_KHAKI 0x00F0E68C
GRAPHICS_COLOR_LAVENDER
#define GRAPHICS_COLOR_LAVENDER 0x00E6E6FA
GRAPHICS_COLOR_LAVENDER_BLUSH
#define GRAPHICS_COLOR_LAVENDER_BLUSH 0x00FFF0F5
GRAPHICS_COLOR_LAWN_GREEN
#define GRAPHICS_COLOR_LAWN_GREEN 0x007CFC00
GRAPHICS_COLOR_LEMON_CHIFFON
#define GRAPHICS_COLOR_LEMON_CHIFFON 0x00FFFACD
GRAPHICS_COLOR_LIGHT_BLUE
#define GRAPHICS_COLOR_LIGHT_BLUE 0x00ADD8E6
GRAPHICS_COLOR_LIGHT_CORAL
#define GRAPHICS_COLOR_LIGHT_CORAL 0x00F08080
GRAPHICS_COLOR_LIGHT_CYAN
#define GRAPHICS_COLOR_LIGHT_CYAN 0x00E0FFFF
GRAPHICS_COLOR_LIGHT_GOLDENRON_YELLOW
#define GRAPHICS_COLOR_LIGHT_GOLDENRON_YELLOW 0x00FAFAD2
GRAPHICS_COLOR_LIGHT_GREEN
#define GRAPHICS_COLOR_LIGHT_GREEN 0x0090EE90
GRAPHICS_COLOR_LIGHT_GRAY
#define GRAPHICS_COLOR_LIGHT_GRAY 0x00D3D3D3
GRAPHICS_COLOR_LIGHT_PINK
#define GRAPHICS_COLOR_LIGHT_PINK 0x00FFB6C1
GRAPHICS_COLOR_LIGHT_SALMON
#define GRAPHICS_COLOR_LIGHT_SALMON 0x00FFA07A
GRAPHICS_COLOR_LIGHT_SEA_GREEN
#define GRAPHICS_COLOR_LIGHT_SEA_GREEN 0x0020B2AA
GRAPHICS_COLOR_LIGHT_SKY_BLUE
#define GRAPHICS_COLOR_LIGHT_SKY_BLUE 0x0087CEFA
GRAPHICS_COLOR_LIGHT_SLATE_GRAY
#define GRAPHICS_COLOR_LIGHT_SLATE_GRAY 0x00778899
GRAPHICS_COLOR_LIGHT_STEEL_BLUE
#define GRAPHICS_COLOR_LIGHT_STEEL_BLUE 0x00B0C4DE
GRAPHICS_COLOR_LIGHT_YELLOW
#define GRAPHICS_COLOR_LIGHT_YELLOW 0x00FFFFE0
GRAPHICS_COLOR_LIME
#define GRAPHICS_COLOR_LIME 0x0000FF00
GRAPHICS_COLOR_LIME_GREEN
#define GRAPHICS_COLOR_LIME_GREEN 0x0032CD32
GRAPHICS_COLOR_LINEN
#define GRAPHICS_COLOR_LINEN 0x00FAF0E6
GRAPHICS_COLOR_MAGENTA
#define GRAPHICS_COLOR_MAGENTA 0x00FF00FF
GRAPHICS_COLOR_MAROON
#define GRAPHICS_COLOR_MAROON 0x00800000
GRAPHICS_COLOR_MEDIUM_AQUAMARINE
#define GRAPHICS_COLOR_MEDIUM_AQUAMARINE 0x0066CDAA
GRAPHICS_COLOR_MEDIUM_BLUE
#define GRAPHICS_COLOR_MEDIUM_BLUE 0x000000CD
GRAPHICS_COLOR_MEDIUM_ORCHID
#define GRAPHICS_COLOR_MEDIUM_ORCHID 0x00BA55D3
GRAPHICS_COLOR_MEDIUM_PURPLE
#define GRAPHICS_COLOR_MEDIUM_PURPLE 0x009370DB
GRAPHICS_COLOR_MEDIUM_SEA_GREEN
#define GRAPHICS_COLOR_MEDIUM_SEA_GREEN 0x003CB371
GRAPHICS_COLOR_MEDIUM_SLATE_BLUE
#define GRAPHICS_COLOR_MEDIUM_SLATE_BLUE 0x007B68EE
GRAPHICS_COLOR_MEDIUM_SPRING_GREEN
#define GRAPHICS_COLOR_MEDIUM_SPRING_GREEN 0x0000FA9A
GRAPHICS_COLOR_MEDIUM_TURQUOISE
#define GRAPHICS_COLOR_MEDIUM_TURQUOISE 0x0048D1CC
GRAPHICS_COLOR_MEDIUM_VIOLET_RED
#define GRAPHICS_COLOR_MEDIUM_VIOLET_RED 0x00C71585
GRAPHICS_COLOR_MIGNIGHT_BLUE
#define GRAPHICS_COLOR_MIGNIGHT_BLUE 0x00191970
GRAPHICS_COLOR_MINT_CREAM
#define GRAPHICS_COLOR_MINT_CREAM 0x00F5FFFA
GRAPHICS_COLOR_MISTY_ROSE
#define GRAPHICS_COLOR_MISTY_ROSE 0x00FFE4E1
GRAPHICS_COLOR_MOCCASIN
#define GRAPHICS_COLOR_MOCCASIN 0x00FFE4B5
GRAPHICS_COLOR_NAVAJO_WHITE
#define GRAPHICS_COLOR_NAVAJO_WHITE 0x00FFDEAD
GRAPHICS_COLOR_NAVY
#define GRAPHICS_COLOR_NAVY 0x00000080
GRAPHICS_COLOR_OLD_LACE
#define GRAPHICS_COLOR_OLD_LACE 0x00FDF5E6
GRAPHICS_COLOR_OLIVE
#define GRAPHICS_COLOR_OLIVE 0x00808000
GRAPHICS_COLOR_OLIVE_DRAB
#define GRAPHICS_COLOR_OLIVE_DRAB 0x006B8E23
GRAPHICS_COLOR_ORANGE
#define GRAPHICS_COLOR_ORANGE 0x00FFA500
GRAPHICS_COLOR_ORANGE_RED
#define GRAPHICS_COLOR_ORANGE_RED 0x00FF4500
GRAPHICS_COLOR_ORCHID
#define GRAPHICS_COLOR_ORCHID 0x00DA70D6
GRAPHICS_COLOR_PALE_GOLDENRON
#define GRAPHICS_COLOR_PALE_GOLDENRON 0x00EEE8AA
GRAPHICS_COLOR_PALE_GREEN
#define GRAPHICS_COLOR_PALE_GREEN 0x0098FB98
GRAPHICS_COLOR_PALE_TURQUOISE
#define GRAPHICS_COLOR_PALE_TURQUOISE 0x00AFEEEE
GRAPHICS_COLOR_PALE_VIOLET_RED
#define GRAPHICS_COLOR_PALE_VIOLET_RED 0x00DB7093
GRAPHICS_COLOR_PAPAYA_WHIP
#define GRAPHICS_COLOR_PAPAYA_WHIP 0x00FFEFD5
GRAPHICS_COLOR_PEACH_PUFF
#define GRAPHICS_COLOR_PEACH_PUFF 0x00FFDAB9
GRAPHICS_COLOR_PERU
#define GRAPHICS_COLOR_PERU 0x00CD853F
GRAPHICS_COLOR_PINK
#define GRAPHICS_COLOR_PINK 0x00FFC0CB
GRAPHICS_COLOR_PLUM
#define GRAPHICS_COLOR_PLUM 0x00DDA0DD
GRAPHICS_COLOR_POWDER_BLUE
#define GRAPHICS_COLOR_POWDER_BLUE 0x00B0E0E6
GRAPHICS_COLOR_PURPLE
#define GRAPHICS_COLOR_PURPLE 0x00800080
GRAPHICS_COLOR_RED
#define GRAPHICS_COLOR_RED 0x00FF0000
GRAPHICS_COLOR_ROSY_BROWN
#define GRAPHICS_COLOR_ROSY_BROWN 0x00BC8F8F
GRAPHICS_COLOR_ROYAL_BLUE
#define GRAPHICS_COLOR_ROYAL_BLUE 0x004169E1
GRAPHICS_COLOR_SADDLE_BROWN
#define GRAPHICS_COLOR_SADDLE_BROWN 0x008B4513
GRAPHICS_COLOR_SALMON
#define GRAPHICS_COLOR_SALMON 0x00FA8072
GRAPHICS_COLOR_SANDY_BROWN
#define GRAPHICS_COLOR_SANDY_BROWN 0x00F4A460
GRAPHICS_COLOR_SEA_GREEN
#define GRAPHICS_COLOR_SEA_GREEN 0x002E8B57
GRAPHICS_COLOR_SEASHELL
#define GRAPHICS_COLOR_SEASHELL 0x00FFF5EE
GRAPHICS_COLOR_SIENNA
#define GRAPHICS_COLOR_SIENNA 0x00A0522D
GRAPHICS_COLOR_SILVER
#define GRAPHICS_COLOR_SILVER 0x00C0C0C0
GRAPHICS_COLOR_SKY_BLUE
#define GRAPHICS_COLOR_SKY_BLUE 0x0087CEEB
GRAPHICS_COLOR_SLATE_BLUE
#define GRAPHICS_COLOR_SLATE_BLUE 0x006A5ACD
GRAPHICS_COLOR_SLATE_GRAY
#define GRAPHICS_COLOR_SLATE_GRAY 0x00708090
GRAPHICS_COLOR_SNOW
#define GRAPHICS_COLOR_SNOW 0x00FFFAFA
GRAPHICS_COLOR_SPRING_GREEN
#define GRAPHICS_COLOR_SPRING_GREEN 0x0000FF7F
GRAPHICS_COLOR_STEEL_BLUE
#define GRAPHICS_COLOR_STEEL_BLUE 0x004682B4
GRAPHICS_COLOR_TAN
#define GRAPHICS_COLOR_TAN 0x00D2B48C
GRAPHICS_COLOR_TEAL
#define GRAPHICS_COLOR_TEAL 0x00008080
GRAPHICS_COLOR_THISTLE
#define GRAPHICS_COLOR_THISTLE 0x00D8BFD8
GRAPHICS_COLOR_TOMATO
#define GRAPHICS_COLOR_TOMATO 0x00FF6347
GRAPHICS_COLOR_TURQUOISE
#define GRAPHICS_COLOR_TURQUOISE 0x0040E0D0
GRAPHICS_COLOR_VIOLET
#define GRAPHICS_COLOR_VIOLET 0x00EE82EE
GRAPHICS_COLOR_WHEAT
#define GRAPHICS_COLOR_WHEAT 0x00F5DEB3
GRAPHICS_COLOR_WHITE
#define GRAPHICS_COLOR_WHITE 0x00FFFFFF
GRAPHICS_COLOR_WHITE_SMOKE
#define GRAPHICS_COLOR_WHITE_SMOKE 0x00F5F5F5
GRAPHICS_COLOR_YELLOW
#define GRAPHICS_COLOR_YELLOW 0x00FFFF00
GRAPHICS_COLOR_YELLOW_GREEN
#define GRAPHICS_COLOR_YELLOW_GREEN 0x009ACD32
ClrRedMask
#define ClrRedMask 0x00FF0000
ClrRedShift
#define ClrRedShift 16
ClrGreenMask
#define ClrGreenMask 0x0000FF00
ClrGreenShift
#define ClrGreenShift 8
ClrBlueMask
#define ClrBlueMask 0x000000FF
ClrBlueShift
#define ClrBlueShift 0
GrLangZhPRC
#define GrLangZhPRC 0x0804
GrLangZhTW
#define GrLangZhTW 0x0404
GrLangEnUS
#define GrLangEnUS 0x0409
GrLangEnUK
#define GrLangEnUK 0x0809
GrLangEnAUS
#define GrLangEnAUS 0x0C09
GrLangEnCA
#define GrLangEnCA 0x1009
GrLangEnNZ
#define GrLangEnNZ 0x1409
GrLangFr
#define GrLangFr 0x040C
GrLangDe
#define GrLangDe 0x0407
GrLangHi
#define GrLangHi 0x0439
GrLangIt
#define GrLangIt 0x0410
GrLangJp
#define GrLangJp 0x0411
GrLangKo
#define GrLangKo 0x0412
GrLangEsMX
#define GrLangEsMX 0x080A
GrLangEsSP
#define GrLangEsSP 0x0C0A
GrLangSwKE
#define GrLangSwKE 0x0441
GrLangUrIN
#define GrLangUrIN 0x0820
GrLangUrPK
#define GrLangUrPK 0x0420
Typedef Documentation
Graphics_Image
typedef struct Graphics_Image Graphics_Image
This structure defines the characteristics of a Bitmap Image.
Graphics_Rectangle
typedef struct Graphics_Rectangle Graphics_Rectangle
This structure defines the extents of a rectangle. All points greater than or equal to the minimum and less than or equal to the maximum are part of the rectangle.
Graphics_Display
typedef struct Graphics_Display Graphics_Display
Graphics_Display_Functions
typedef struct Graphics_Display_Functions Graphics_Display_Functions
This structure defines the implementation of a display driver.
Graphics_Font
typedef struct Graphics_Font Graphics_Font
This structure describes a font used for drawing text onto the screen.
Graphics_FontEx
typedef struct Graphics_FontEx Graphics_FontEx
This is a newer version of the structure which describes a font used for drawing text onto the screen. This variant allows a font to contain an arbitrary, contiguous block of codepoints from the 256 basic characters in an ISO8859-n font and allows support for accented characters in Western European languages and any left-to-right typeface supported by an ISO8859 variant. Fonts encoded in this format may be used interchangeably with the original fonts merely by casting the structure pointer when calling any function or macro which expects a font pointer as a parameter.
Graphics_Context
typedef struct Graphics_Context Graphics_Context
This structure defines a drawing context to be used to draw onto the screen. Multiple drawing contexts may exist at any time.
Function Documentation
Graphics_drawCircle()
void Graphics_drawCircle (const Graphics_Context * context, int32_t x, int32_t y, int32_t radius)
Draws a circle.
Parameters
context is a pointer to the drawing context to use.
x is the X coordinate of the center of the circle.
y is the Y coordinate of the center of the circle.
radius is the radius of the circle.
This function draws a circle, utilizing the Bresenham circle drawing algorithm. The extent of the circle is from x - radius to x + radius and y - radius to y + radius, inclusive.
Returns
None.
References Graphics_Context::clipRegion, Graphics_drawPixel(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawRadioButton().
Graphics_fillCircle()
void Graphics_fillCircle (const Graphics_Context * context, int32_t x, int32_t y, int32_t radius)
Draws a filled circle.
Parameters
context is a pointer to the drawing context to use.
x is the X coordinate of the center of the circle.
y is the Y coordinate of the center of the circle.
radius is the radius of the circle.
This function draws a filled circle, utilizing the Bresenham circle drawing algorithm. The extent of the circle is from x - radius to x + radius and y - radius to y + radius, inclusive.
Returns
None.
References Graphics_Context::clipRegion, Graphics_drawLineH(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawRadioButton(), Graphics_drawReleasedRadioButton(), and Graphics_drawSelectedRadioButton().
Graphics_setClipRegion()
void Graphics_setClipRegion (Graphics_Context * context, Graphics_Rectangle * rect)
Sets the extents of the clipping region.
Parameters
context is a pointer to the drawing context to use.
rect is a pointer to the structure containing the extents of the clipping region.
This function sets the extents of the clipping region. The clipping region is not allowed to exceed the extents of the screen, but may be a portion of the screen.
The supplied coordinate are inclusive; xMin of 1 and xMax of 1 will define a clipping region that will display only the pixels in the X = 1 column. A consequence of this is that the clipping region must contain at least one row and one column.
Returns
None.
References Graphics_Context::clipRegion, Graphics_Context::display, Graphics_getHeightOfDisplay(), Graphics_getWidthOfDisplay(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Graphics_initContext()
void Graphics_initContext (Graphics_Context * context, Graphics_Display * display, const Graphics_Display_Functions * pFxns)
Initializes a drawing context.
Parameters
context is a pointer to the drawing context to initialize.
display is a pointer to the Graphics_Display Info structure that describes the display driver to use.
pFxns isa pointer to driver functions.
This function initializes a drawing context, preparing it for use. The provided display driver will be used for all subsequent graphics operations, and the default clipping region will be set to the extent of the screen.
Returns
None.
References Graphics_Context::background, Graphics_Context::clipRegion, Graphics_Context::display, Graphics_Context::font, Graphics_Context::foreground, Graphics_Display::heigth, Graphics_Display::pFxns, Graphics_Context::size, Graphics_Display::width, Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Graphics_drawImage()
void Graphics_drawImage (const Graphics_Context * context, const Graphics_Image * bitmap, int16_t x, int16_t y)
Draws a bitmap image.
Parameters
context is a pointer to the drawing context to use.
bitmap is a pointer to the image to draw.
x is the X coordinate of the upper left corner of the image.
y is the Y coordinate of the upper left corner of the image.
This function draws a bitmap image. The image may be 1 bit per pixel, 4 bits per pixel or 8 bits per pixel (using a palette supplied in the image data). It can be uncompressed data, or it can be compressed using several different compression types. Compression options are 4-bit run length encoding, 8-bit run length encoding, and a custom run length encoding variation written for complex 8-bit per pixel images.
Returns
None.
References Graphics_Image::bPP, Graphics_Context::clipRegion, Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Image::xSize, Graphics_Rectangle::yMax, Graphics_Rectangle::yMin, and Graphics_Image::ySize.
Referenced by Graphics_drawImageButton(), Graphics_drawReleasedImageButton(), and Graphics_drawSelectedImageButton().
Graphics_drawLine()
void Graphics_drawLine (const Graphics_Context * context, int32_t x1, int32_t y1, int32_t x2, int32_t y2)
Draws a line.
Parameters
context is a pointer to the drawing context to use.
x1 is the X coordinate of the start of the line.
y1 is the Y coordinate of the start of the line.
x2 is the X coordinate of the end of the line.
y2 is the Y coordinate of the end of the line.
This function draws a line, utilizing Graphics_drawLineH() and Graphics_drawLineV() to draw the line as efficiently as possible. The line is clipped to the clippping rectangle using the Cohen-Sutherland clipping algorithm, and then scan converted using Bresenham's line drawing algorithm.
Returns
None.
References Graphics_drawLineH(), and Graphics_drawLineV().
Referenced by Graphics_drawCheckBox(), and Graphics_drawSelectedCheckBox().
Graphics_drawLineH()
void Graphics_drawLineH (const Graphics_Context * context, int32_t x1, int32_t x2, int32_t y)
Draws a horizontal line.
Parameters
context is a pointer to the drawing context to use.
x1 is the X coordinate of one end of the line.
x2 is the X coordinate of the other end of the line.
y is the Y coordinate of the line.
This function draws a horizontal line, taking advantage of the fact that the line is horizontal to draw it more efficiently. The clipping of the horizontal line to the clipping rectangle is performed within this routine; the display driver's horizontal line routine is used to perform the actual line drawing.
Returns
None.
References Graphics_Context::clipRegion, Graphics_Context::display, Graphics_Context::foreground, Graphics_drawHorizontalLineOnDisplay(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, and Graphics_Rectangle::yMax.
Referenced by Graphics_drawLine(), Graphics_drawRectangle(), and Graphics_fillCircle().
Graphics_drawLineV()
void Graphics_drawLineV (const Graphics_Context * context, int32_t x, int32_t y1, int32_t y2)
Draws a vertical line.
Parameters
context is a pointer to the drawing context to use.
x is the X coordinate of the line.
y1 is the Y coordinate of one end of the line.
y2 is the Y coordinate of the other end of the line.
This function draws a vertical line, taking advantage of the fact that the line is vertical to draw it more efficiently. The clipping of the vertical line to the clipping rectangle is performed within this routine; the display driver's vertical line routine is used to perform the actual line drawing.
Returns
None.
References Graphics_Context::clipRegion, Graphics_Context::display, Graphics_Context::foreground, Graphics_drawVerticalLineOnDisplay(), Graphics_Rectangle::xMax, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawLine(), and Graphics_drawRectangle().
Graphics_drawRectangle()
void Graphics_drawRectangle (const Graphics_Context * context, const Graphics_Rectangle * rect)
Draws a rectangle.
Parameters
context is a pointer to the drawing context to use.
rect is a pointer to the structure containing the extents of the rectangle.
This function draws a rectangle. The rectangle will extend from xMin to xMax and yMin to yMax, inclusive.
Returns
None.
References Graphics_drawLineH(), Graphics_drawLineV(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawCheckBox(), and Graphics_drawReleasedCheckBox().
Graphics_fillRectangle()
void Graphics_fillRectangle (const Graphics_Context * context, const Graphics_Rectangle * rect)
Draws a filled rectangle.
Parameters
context is a pointer to the drawing context to use.
rect is a pointer to the structure containing the extents of the rectangle.
This function draws a filled rectangle. The rectangle will extend from xMin to xMax and yMin to yMax, inclusive. The clipping of the rectangle to the clipping rectangle is performed within this routine; the display driver's rectangle fill routine is used to perform the actual rectangle fill.
Returns
None.
References Graphics_Context::clipRegion, Graphics_Context::display, Graphics_Context::foreground, Graphics_fillRectangleOnDisplay(), Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawCheckBox(), Graphics_drawImageButton(), Graphics_drawReleasedCheckBox(), Graphics_drawReleasedImageButton(), and Graphics_drawSelectedImageButton().
Graphics_drawString()
void Graphics_drawString (const Graphics_Context * context, int8_t * string, int32_t length, int32_t x, int32_t y, bool opaque)
Draws a string.
Parameters
context is a pointer to the drawing context to use.
string is a pointer to the string to be drawn.
length is the number of characters from the string that should be drawn on the screen.
x is the X coordinate of the upper left corner of the string position on the screen.
y is the Y coordinate of the upper left corner of the string position on the screen.
opaque is true if the background of each character should be drawn and false if it should not (leaving the background as is).
This function draws a string of test on the screen. The length parameter allows a portion of the string to be examined without having to insert a NULL character at the stopping point (which would not be possible if the string was located in flash); specifying a length of -1 will cause the entire string to be rendered (subject to clipping).
Returns
None.
References Graphics_Context::clipRegion, Graphics_Font::data, Graphics_FontEx::data, Graphics_FontEx::first, Graphics_Context::font, Graphics_Font::format, GRAPHICS_ABSENT_CHAR_REPLACEMENT, GRAPHICS_FONT_EX_MARKER, GRAPHICS_FONT_FMT_UNCOMPRESSED, Graphics_FontEx::last, Graphics_Font::offset, Graphics_FontEx::offset, Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, and Graphics_Rectangle::yMax.
Referenced by Graphics_drawCheckBox(), Graphics_drawRadioButton(), and Graphics_drawStringCentered().
Graphics_getStringWidth()
int32_t Graphics_getStringWidth (const Graphics_Context * context, const int8_t * string, int32_t length)
Determines the width of a string.
Parameters
context is a pointer to the drawing context to use.
string is the string in question.
length is the length of the string.
This function determines the width of a string (or portion of the string) when drawn with a particular font. The length parameter allows a portion of the string to be examined without having to insert a NULL character at the stopping point (would not be possible if the string was located in flash); specifying a length of -1 will cause the width of the entire string to be computed.
Returns
Returns the width of the string in pixels.
References Graphics_Font::data, Graphics_FontEx::data, Graphics_FontEx::first, Graphics_Context::font, Graphics_Font::format, GRAPHICS_ABSENT_CHAR_REPLACEMENT, GRAPHICS_FONT_EX_MARKER, Graphics_FontEx::last, Graphics_Font::offset, and Graphics_FontEx::offset.
Referenced by Graphics_drawStringCentered().
Graphics_isOverlappingRectangle()
int32_t Graphics_isOverlappingRectangle (Graphics_Rectangle * psRect1, Graphics_Rectangle * psRect2)
Graphics_getRectangleIntersection()
int32_t Graphics_getRectangleIntersection (Graphics_Rectangle * rect1, Graphics_Rectangle * rect2, Graphics_Rectangle * intersect)
Determines the intersection of two rectangles.
Parameters
rect1 is a pointer to the first rectangle.
rect2 is a pointer to the second rectangle.
intersect is a pointer to a rectangle which will be written with the intersection of rect1 and rect2.
This function determines if two rectangles overlap and, if they do, calculates the rectangle representing their intersection. If the rectangles do not overlap, 0 is returned and intersect is not written.
Returns
Returns 1 if there is an overlap or 0 if not.
References Graphics_isRectangleOverlap(), max, min, Graphics_Rectangle::xMax, Graphics_Rectangle::xMin, Graphics_Rectangle::yMax, and Graphics_Rectangle::yMin.
Graphics_setBackgroundColor()
void Graphics_setBackgroundColor (Graphics_Context * context, int32_t value)
Sets the background color to be used.
Parameters
context is a pointer to the drawing context to modify.
value is the 24-bit RGB color to be used.
This function sets the background color to be used for drawing operations in the specified drawing context.
Returns
None.
References Graphics_Context::background, Graphics_Context::display, and Graphics_translateColorOnDisplay().
Graphics_getDisplayWidth()
uint16_t Graphics_getDisplayWidth (Graphics_Context * context)
Gets the width of the display being used by this drawing context.
Parameters
context is a pointer to the drawing context to query.
This function returns the width of the display that is being used by this drawing context.
Returns
Returns the width of the display in pixels.
References Graphics_Context::display, and Graphics_Display::width.
Graphics_getDisplayHeight()
uint16_t Graphics_getDisplayHeight (Graphics_Context * context)
Gets the height of the display being used by this drawing context.
Parameters
context is a pointer to the drawing context to query.
This function returns the height of the display that is being used by this drawing context.
Returns
Returns the height of the display in pixels.
References Graphics_Context::display, and Graphics_Display::heigth.
Graphics_setFont()
void Graphics_setFont (Graphics_Context * context, const Graphics_Font * font)
Sets the font to be used.
Parameters
context is a pointer to the drawing context to modify.
font is a pointer to the font to be used.
This function sets the font to be used for string drawing operations in the specified drawing context. If a tFontEx type font is to be used, cast its pointer to a font pointer before passing it as the font parameter.
Returns
None.
References Graphics_Context::font.
Referenced by Graphics_drawCheckBox(), Graphics_drawImageButton(), Graphics_drawRadioButton(), Graphics_drawReleasedImageButton(), Graphics_drawSelectedImageButton(), and Graphics_drawSelectedRadioButton().
Graphics_getFontBaseline()
uint8_t Graphics_getFontBaseline (const Graphics_Font * font)
Gets the baseline of a font.
Parameters
font is a pointer to the font to query.
This function determines the baseline position of a font. The baseline is the offset between the top of the font and the bottom of the capital letters. The only font data that exists below the baseline are the descenders on some lower-case letters (such as ``y'').
Returns
Returns the baseline of the font, in pixels.
References Graphics_Font::baseline.
Graphics_setForegroundColor()
void Graphics_setForegroundColor (Graphics_Context * context, int32_t value)
Sets the foreground color to be used.
Parameters
context is a pointer to the drawing context to modify.
value is the 24-bit RGB color to be used.
This function sets the color to be used for drawing operations in the specified drawing context.
Returns
None.
References Graphics_Context::display, Graphics_Context::foreground, and Graphics_translateColorOnDisplay().
Referenced by Graphics_drawCheckBox(), Graphics_drawImageButton(), Graphics_drawRadioButton(), Graphics_drawReleasedCheckBox(), Graphics_drawReleasedImageButton(), Graphics_drawReleasedRadioButton(), Graphics_drawSelectedCheckBox(), Graphics_drawSelectedImageButton(), and Graphics_drawSelectedRadioButton().
Graphics_setForegroundColorTranslated()
void Graphics_setForegroundColorTranslated (Graphics_Context * context, int32_t value)
Sets the foreground color to be used.
Parameters
context is a pointer to the drawing context to modify.
value is the display driver-specific color to be used.
This function sets the foreground color to be used for drawing operations in the specified drawing context, using a color that has been previously translated to a driver-specific color (for example, via Graphics_translateColorDisplay()).
Returns
None.
References Graphics_Context::foreground.
Graphics_getFontHeight()
uint8_t Graphics_getFontHeight (const Graphics_Font * font)
Gets the height of a font.
Parameters
font is a pointer to the font to query.
This function determines the height of a font. The height is the offset between the top of the font and the bottom of the font, including any ascenders and descenders.
Returns
Returns the height of the font, in pixels.
References Graphics_Font::height.
Graphics_getFontMaxWidth()
uint8_t Graphics_getFontMaxWidth (const Graphics_Font * font)
Gets the maximum width of a font.
Parameters
font is a pointer to the font to query.
This function determines the maximum width of a font. The maximum width is the width of the widest individual character in the font.
Returns
Returns the maximum width of the font, in pixels.
References Graphics_Font::maxWidth.
Graphics_getImageColors()
uint16_t Graphics_getImageColors (const Graphics_Image * image)
Gets the number of colors in an image.
Parameters
image is a tImage struct
This function determines the number of colors in the palette of an image. This is only valid for 4bpp and 8bpp images; 1bpp images do not contain a palette.
Returns
Returns the number of colors in the image.
References Graphics_Image::numColors.
Graphics_getImageHeight()
uint16_t Graphics_getImageHeight (const Graphics_Image * image)
Gets the height of an image.
Parameters
image is a tImage struct
This function determines the height of an image in pixels.
Returns
Returns the height of the image in pixels.
References Graphics_Image::ySize.
Graphics_getImageWidth()
uint16_t Graphics_getImageWidth (const Graphics_Image * image)
Gets the width of an image.
Parameters
image is a tImage struct
This function determines the width of an image in pixels.
Returns
Returns the width of the image in pixels.
References Graphics_Image::xSize.
Graphics_getOffscreen1BppImageSize()
uint32_t Graphics_getOffscreen1BppImageSize (uint16_t width, uint16_t height)
Determines the size of the buffer for a 1 BPP off-screen image.
Parameters
width is the width of the image in pixels.
height is the height of the image in pixels.
This function determines the size of the memory buffer required to hold a 1 BPP off-screen image of the specified geometry.
Returns
Returns the number of bytes required by the image.
Graphics_getOffscreen4BppImageSize()
uint32_t Graphics_getOffscreen4BppImageSize (uint16_t width, uint16_t height)
Determines the size of the buffer for a 4 BPP off-screen image.
Parameters
width is the width of the image in pixels.
height is the height of the image in pixels.
This function determines the size of the memory buffer required to hold a 4 BPP off-screen image of the specified geometry.
Returns
Returns the number of bytes required by the image.
Graphics_getOffScreen8BPPSize()
uint32_t Graphics_getOffScreen8BPPSize (uint16_t width, uint16_t height)
Determines the size of the buffer for an 8 BPP off-screen image.
Parameters
width is the width of the image in pixels.
height is the height of the image in pixels.
This function determines the size of the memory buffer required to hold an 8 BPP off-screen image of the specified geometry.
Returns
Returns the number of bytes required by the image.
Graphics_drawStringCentered()
void Graphics_drawStringCentered (const Graphics_Context * context, int8_t * string, int32_t length, int32_t x, int32_t y, bool opaque)
Draws a centered string.
Parameters
context is a pointer to the drawing context to use.
string is a pointer to the string to be drawn.
length is the number of characters from the string that should be drawn on the screen.
x is the X coordinate of the center of the string position on the screen.
y is the Y coordinate of the center of the string position on the screen.
opaque is true if the background of each character should be drawn and false if it should not (leaving the background as is).
This function draws a string of test on the screen centered upon the provided position. The lLength parameter allows a portion of the string to be examined without having to insert a NULL character at the stopping point (which would not be possible if the string was located in flash); specifying a length of -1 will cause the entire string to be rendered (subject to clipping).
Returns
None.
References Graphics_Font::baseline, Graphics_Context::font, Graphics_drawString(), and Graphics_getStringWidth().
Graphics_getStringHeight()
uint8_t Graphics_getStringHeight (const Graphics_Context * context)
Gets the height of a string.
Parameters
context is a pointer to the drawing context to query.
This function determines the height of a string. The height is the offset between the top of the string and the bottom of the string, including any ascenders and descenders. Note that this will not account for the case where the string in question does not have any characters that use descenders but the font in the drawing context does contain characters with descenders.
Returns
Returns the height of the string, in pixels.
References Graphics_Context::font, and Graphics_Font::height.
Graphics_getStringMaxWidth()
uint8_t Graphics_getStringMaxWidth (const Graphics_Context * context)
Gets the maximum width of a character in a string.
Parameters
context is a pointer to the drawing context to query.
This function determines the maximum width of a character in a string. The maximum width is the width of the widest individual character in the font used to render the string, which may be wider than the widest character that is used to render a particular string.
Returns
Returns the maximum width of a character in a string, in pixels.
References Graphics_Context::font, and Graphics_Font::maxWidth.
Graphics_getStringBaseline()
uint8_t Graphics_getStringBaseline (const Graphics_Context * context)
Gets the baseline of a string.
Parameters
context is a pointer to the drawing context to query.
This function determines the baseline position of a string. The baseline is the offset between the top of the string and the bottom of the capital letters. The only string data that exists below the baseline are the descenders on some lower-case letters (such as ``y'').
Returns
Returns the baseline of the string, in pixels.
References Graphics_Font::baseline, and Graphics_Context::font.
Graphics_translateColorOnDisplay()
uint32_t Graphics_translateColorOnDisplay (const Graphics_Display * display, uint32_t value)
Translates a 24-bit RGB color to a display driver-specific color.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
value is the 24-bit RGB color. The least-significant byte is the blue channel, the next byte is the green channel, and the third byte is the red channel.
This function translates a 24-bit RGB color into a value that can be written into the display's frame buffer in order to reproduce that color, or the closest possible approximation of that color.
Returns
Returns the display-driver specific color.
References Graphics_Display_Functions::pfnColorTranslate, and Graphics_Display::pFxns.
Referenced by Graphics_setBackgroundColor(), and Graphics_setForegroundColor().
Graphics_drawHorizontalLineOnDisplay()
void Graphics_drawHorizontalLineOnDisplay (const Graphics_Display * display, uint16_t x1, uint16_t x2, uint16_t y, uint32_t value)
Draws a horizontal line on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x1 is the starting X coordinate of the line.
x2 is the ending X coordinate of the line.
y is the Y coordinate of the line.
value is the color to draw the line.
This function draws a horizontal line on a display. This assumes that clipping has already been performed, and that both end points of the line are within the extents of the display.
Returns
None.
References Graphics_Display_Functions::pfnLineDrawH, and Graphics_Display::pFxns.
Referenced by Graphics_drawLineH().
Graphics_drawVerticalLineOnDisplay()
void Graphics_drawVerticalLineOnDisplay (const Graphics_Display * display, uint16_t x, uint16_t y1, uint16_t y2, uint16_t value)
Draws a vertical line on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x is the X coordinate of the line.
y1 is the starting Y coordinate of the line.
y2 is the ending Y coordinate of the line.
value is the color to draw the line.
This function draws a vertical line on a display. This assumes that clipping has already been performed, and that both end points of the line are within the extents of the display.
Returns
None.
References Graphics_Display_Functions::pfnLineDrawV, and Graphics_Display::pFxns.
Referenced by Graphics_drawLineV().
Graphics_fillRectangleOnDisplay()
void Graphics_fillRectangleOnDisplay (const Graphics_Display * display, const Graphics_Rectangle * rect, uint16_t value)
Fills a rectangle on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
rect is a pointer to the structure describing the rectangle to fill.
value is the color to fill the rectangle.
This function fills a rectangle on the display. This assumes that clipping has already been performed, and that all sides of the rectangle are within the extents of the display.
Returns
None.
References Graphics_Display_Functions::pfnRectFill, and Graphics_Display::pFxns.
Referenced by Graphics_fillRectangle().
Graphics_flushOnDisplay()
void Graphics_flushOnDisplay (const Graphics_Display * display)
Flushes cached drawing operations.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
This function flushes any cached drawing operations on a display.
Returns
None.
References Graphics_Display_Functions::pfnFlush, and Graphics_Display::pFxns.
Referenced by Graphics_flushBuffer().
Graphics_drawPixel()
void Graphics_drawPixel (const Graphics_Context * context, uint16_t x, uint16_t y)
Draws a pixel.
Parameters
context is a pointer to the drawing context to use.
x is the X coordinate of the pixel.
y is the Y coordinate of the pixel.
This function draws a pixel if it resides within the clipping region.
Returns
None.
References Graphics_Context::clipRegion, Graphics_Context::display, Graphics_Context::foreground, Graphics_drawPixelOnDisplay(), Graphics_Rectangle::xMin, and Graphics_Rectangle::yMin.
Referenced by Graphics_drawCircle().
Graphics_clearDisplay()
void Graphics_clearDisplay (const Graphics_Context * context)
Forces a clear screen. Contents of Display buffer unmodified
Parameters
context is a pointer to the drawing context to use.
This function forces a clear screen.
Returns
None.
References Graphics_Context::background, Graphics_Context::display, and Graphics_clearDisplayOnDisplay().
Graphics_getHeightOfDisplay()
uint16_t Graphics_getHeightOfDisplay (const Graphics_Display * display)
Gets the height of the display.
Parameters
display is a pointer to the display driver structure for the display to query.
This function determines the height of the display.
Returns
Returns the height of the display in pixels.
References Graphics_Display::heigth.
Referenced by Graphics_setClipRegion().
Graphics_flushBuffer()
void Graphics_flushBuffer (const Graphics_Context * context)
Flushes any cached drawing operations.
Parameters
context is a pointer to the drawing context to use.
This function flushes any cached drawing operations. For display drivers that draw into a local frame buffer before writing to the actual display, calling this function will cause the display to be updated to match the contents of the local frame buffer.
Returns
None.
References Graphics_Context::display, and Graphics_flushOnDisplay().
Graphics_getWidthOfDisplay()
uint16_t Graphics_getWidthOfDisplay (const Graphics_Display * display)
Gets the width of the display.
Parameters
display is a pointer to the display driver structure for the display to query.
This function determines the width of the display.
Returns
Returns the width of the display in pixels.
References Graphics_Display::width.
Referenced by Graphics_setClipRegion().
Graphics_isPointWithinRectangle()
bool Graphics_isPointWithinRectangle (const Graphics_Rectangle * rect, uint16_t x, uint16_t y)
Determines if a point lies within a given rectangle.
Parameters
rect is a pointer to the rectangle which the point is to be checked against.
x is the X coordinate of the point to be checked.
y is the Y coordinate of the point to be checked.
This function determines whether point (x, y) lies within the rectangle described by rect.
Returns
Returns 1 if the point is within the rectangle or 0 otherwise.
Graphics_drawPixelOnDisplay()
void Graphics_drawPixelOnDisplay (const Graphics_Display * display, uint16_t x, uint16_t y, uint16_t value)
Draws a pixel on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x is the X coordinate of the pixel.
y is the Y coordinate of the pixel.
value is the color to draw the pixel.
This function draws a pixel on a display. This assumes that clipping has already been performed.
Returns
None.
References Graphics_Display_Functions::pfnPixelDraw, and Graphics_Display::pFxns.
Referenced by Graphics_drawPixel().
Graphics_clearDisplayOnDisplay()
void Graphics_clearDisplayOnDisplay (const Graphics_Display * display, uint16_t value)
Forces a clear Display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
value is the current background color to fill the screen with.
This function clears the Display
Returns
None.
References Graphics_Display_Functions::pfnClearDisplay, and Graphics_Display::pFxns.
Referenced by Graphics_clearDisplay().
Graphics_drawMultiplePixelsOnDisplay()
void Graphics_drawMultiplePixelsOnDisplay (const Graphics_Display * display, uint16_t x, uint16_t y, uint16_t x0, uint16_t count, uint16_t bPP, const uint8_t * data, const uint32_t * palette)
Draws a horizontal sequence of pixels on a display.
Parameters
display is the pointer to the display driver structure for the display to operate upon.
x is the X coordinate of the first pixel.
y is the Y coordinate of the first pixel.
x0 is sub-pixel offset within the pixel data, which is valid for 1 or 4 bit per pixel formats.
count is the number of pixels to draw.
bPP is the number of bits per pixel; must be 1, 4, or 8.
data is a pointer to the pixel data. For 1 and 4 bit per pixel formats, the most significant bit(s) represent the left-most pixel.
palette is a pointer to the palette used to draw the pixels.
This function draws a horizontal sequence of pixels on a display, using the supplied palette. For 1 bit per pixel format, the palette contains pre-translated colors; for 4 and 8 bit per pixel formats, the palette contains 24-bit RGB values that must be translated before being written to the display.
Returns
None.
References Graphics_Display_Functions::pfnPixelDrawMultiple, and Graphics_Display::pFxns.
Graphics_initOffscreen1BppImage()
void Graphics_initOffscreen1BppImage (Graphics_Display * display, uint8_t * image, int32_t width, int32_t height)
Graphics_initOffscreen4BppImage()
void Graphics_initOffscreen4BppImage (Graphics_Display * display, uint8_t * image, int32_t width, int32_t height)
Graphics_setOffscreen4BppPalette()
void Graphics_setOffscreen4BppPalette (Graphics_Display * display, uint32_t * ppalette, uint32_t offset, uint32_t count)
Graphics_initOffscreen8BppImage()
void Graphics_initOffscreen8BppImage (Graphics_Display * display, uint8_t * image, int32_t width, int32_t height)
Graphics_setOffscreen8BppPalette()
void Graphics_setOffscreen8BppPalette (Graphics_Display * display, uint32_t * ppalette, uint32_t offset, uint32_t count)
Variable Documentation
g_sFontCm12
const Graphics_Font g_sFontCm12
g_sFontCm12b
const Graphics_Font g_sFontCm12b
g_sFontCm12i
const Graphics_Font g_sFontCm12i
g_sFontCm14
const Graphics_Font g_sFontCm14
g_sFontCm14b
const Graphics_Font g_sFontCm14b
g_sFontCm14i
const Graphics_Font g_sFontCm14i
g_sFontCm16
const Graphics_Font g_sFontCm16
g_sFontCm16b
const Graphics_Font g_sFontCm16b
g_sFontCm16i
const Graphics_Font g_sFontCm16i
g_sFontCm18
const Graphics_Font g_sFontCm18
g_sFontCm18b
const Graphics_Font g_sFontCm18b
g_sFontCm18i
const Graphics_Font g_sFontCm18i
g_sFontCm20
const Graphics_Font g_sFontCm20
g_sFontCm20b
const Graphics_Font g_sFontCm20b
g_sFontCm20i
const Graphics_Font g_sFontCm20i
g_sFontCm22
const Graphics_Font g_sFontCm22
g_sFontCm22b
const Graphics_Font g_sFontCm22b
g_sFontCm22i
const Graphics_Font g_sFontCm22i
g_sFontCm24
const Graphics_Font g_sFontCm24
g_sFontCm24b
const Graphics_Font g_sFontCm24b
g_sFontCm24i
const Graphics_Font g_sFontCm24i
g_sFontCm26
const Graphics_Font g_sFontCm26
g_sFontCm26b
const Graphics_Font g_sFontCm26b
g_sFontCm26i
const Graphics_Font g_sFontCm26i
g_sFontCm28
const Graphics_Font g_sFontCm28
g_sFontCm28b
const Graphics_Font g_sFontCm28b
g_sFontCm28i
const Graphics_Font g_sFontCm28i
g_sFontCm30
const Graphics_Font g_sFontCm30
g_sFontCm30b
const Graphics_Font g_sFontCm30b
g_sFontCm30i
const Graphics_Font g_sFontCm30i
g_sFontCm32
const Graphics_Font g_sFontCm32
g_sFontCm32b
const Graphics_Font g_sFontCm32b
g_sFontCm32i
const Graphics_Font g_sFontCm32i
g_sFontCm34
const Graphics_Font g_sFontCm34
g_sFontCm34b
const Graphics_Font g_sFontCm34b
g_sFontCm34i
const Graphics_Font g_sFontCm34i
g_sFontCm36
const Graphics_Font g_sFontCm36
g_sFontCm36b
const Graphics_Font g_sFontCm36b
g_sFontCm36i
const Graphics_Font g_sFontCm36i
g_sFontCm38
const Graphics_Font g_sFontCm38
g_sFontCm38b
const Graphics_Font g_sFontCm38b
g_sFontCm38i
const Graphics_Font g_sFontCm38i
g_sFontCm40
const Graphics_Font g_sFontCm40
g_sFontCm40b
const Graphics_Font g_sFontCm40b
g_sFontCm40i
const Graphics_Font g_sFontCm40i
g_sFontCm42
const Graphics_Font g_sFontCm42
g_sFontCm42b
const Graphics_Font g_sFontCm42b
g_sFontCm42i
const Graphics_Font g_sFontCm42i
g_sFontCm44
const Graphics_Font g_sFontCm44
g_sFontCm44b
const Graphics_Font g_sFontCm44b
g_sFontCm44i
const Graphics_Font g_sFontCm44i
g_sFontCm46
const Graphics_Font g_sFontCm46
g_sFontCm46b
const Graphics_Font g_sFontCm46b
g_sFontCm46i
const Graphics_Font g_sFontCm46i
g_sFontCm48
const Graphics_Font g_sFontCm48
g_sFontCm48b
const Graphics_Font g_sFontCm48b
g_sFontCm48i
const Graphics_Font g_sFontCm48i
g_sFontCmsc12
const Graphics_Font g_sFontCmsc12
g_sFontCmsc14
const Graphics_Font g_sFontCmsc14
g_sFontCmsc16
const Graphics_Font g_sFontCmsc16
g_sFontCmsc18
const Graphics_Font g_sFontCmsc18
g_sFontCmsc20
const Graphics_Font g_sFontCmsc20
g_sFontCmsc22
const Graphics_Font g_sFontCmsc22
g_sFontCmsc24
const Graphics_Font g_sFontCmsc24
g_sFontCmsc26
const Graphics_Font g_sFontCmsc26
g_sFontCmsc28
const Graphics_Font g_sFontCmsc28
g_sFontCmsc30
const Graphics_Font g_sFontCmsc30
g_sFontCmsc32
const Graphics_Font g_sFontCmsc32
g_sFontCmsc34
const Graphics_Font g_sFontCmsc34
g_sFontCmsc36
const Graphics_Font g_sFontCmsc36
g_sFontCmsc38
const Graphics_Font g_sFontCmsc38
g_sFontCmsc40
const Graphics_Font g_sFontCmsc40
g_sFontCmsc42
const Graphics_Font g_sFontCmsc42
g_sFontCmsc44
const Graphics_Font g_sFontCmsc44
g_sFontCmsc46
const Graphics_Font g_sFontCmsc46
g_sFontCmsc48
const Graphics_Font g_sFontCmsc48
g_sFontCmss12
const Graphics_Font g_sFontCmss12
g_sFontCmss12b
const Graphics_Font g_sFontCmss12b
g_sFontCmss12i
const Graphics_Font g_sFontCmss12i
g_sFontCmss14
const Graphics_Font g_sFontCmss14
g_sFontCmss14b
const Graphics_Font g_sFontCmss14b
g_sFontCmss14i
const Graphics_Font g_sFontCmss14i
g_sFontCmss16
const Graphics_Font g_sFontCmss16
g_sFontCmss16b
const Graphics_Font g_sFontCmss16b
g_sFontCmss16i
const Graphics_Font g_sFontCmss16i
g_sFontCmss18
const Graphics_Font g_sFontCmss18
g_sFontCmss18b
const Graphics_Font g_sFontCmss18b
g_sFontCmss18i
const Graphics_Font g_sFontCmss18i
g_sFontCmss20
const Graphics_Font g_sFontCmss20
g_sFontCmss20b
const Graphics_Font g_sFontCmss20b
g_sFontCmss20i
const Graphics_Font g_sFontCmss20i
g_sFontCmss22
const Graphics_Font g_sFontCmss22
g_sFontCmss22b
const Graphics_Font g_sFontCmss22b
g_sFontCmss22i
const Graphics_Font g_sFontCmss22i
g_sFontCmss24
const Graphics_Font g_sFontCmss24
g_sFontCmss24b
const Graphics_Font g_sFontCmss24b
g_sFontCmss24i
const Graphics_Font g_sFontCmss24i
g_sFontCmss26
const Graphics_Font g_sFontCmss26
g_sFontCmss26b
const Graphics_Font g_sFontCmss26b
g_sFontCmss26i
const Graphics_Font g_sFontCmss26i
g_sFontCmss28
const Graphics_Font g_sFontCmss28
g_sFontCmss28b
const Graphics_Font g_sFontCmss28b
g_sFontCmss28i
const Graphics_Font g_sFontCmss28i
g_sFontCmss30
const Graphics_Font g_sFontCmss30
g_sFontCmss30b
const Graphics_Font g_sFontCmss30b
g_sFontCmss30i
const Graphics_Font g_sFontCmss30i
g_sFontCmss32
const Graphics_Font g_sFontCmss32
g_sFontCmss32b
const Graphics_Font g_sFontCmss32b
g_sFontCmss32i
const Graphics_Font g_sFontCmss32i
g_sFontCmss34
const Graphics_Font g_sFontCmss34
g_sFontCmss34b
const Graphics_Font g_sFontCmss34b
g_sFontCmss34i
const Graphics_Font g_sFontCmss34i
g_sFontCmss36
const Graphics_Font g_sFontCmss36
g_sFontCmss36b
const Graphics_Font g_sFontCmss36b
g_sFontCmss36i
const Graphics_Font g_sFontCmss36i
g_sFontCmss38
const Graphics_Font g_sFontCmss38
g_sFontCmss38b
const Graphics_Font g_sFontCmss38b
g_sFontCmss38i
const Graphics_Font g_sFontCmss38i
g_sFontCmss40
const Graphics_Font g_sFontCmss40
g_sFontCmss40b
const Graphics_Font g_sFontCmss40b
g_sFontCmss40i
const Graphics_Font g_sFontCmss40i
g_sFontCmss42
const Graphics_Font g_sFontCmss42
g_sFontCmss42b
const Graphics_Font g_sFontCmss42b
g_sFontCmss42i
const Graphics_Font g_sFontCmss42i
g_sFontCmss44
const Graphics_Font g_sFontCmss44
g_sFontCmss44b
const Graphics_Font g_sFontCmss44b
g_sFontCmss44i
const Graphics_Font g_sFontCmss44i
g_sFontCmss46
const Graphics_Font g_sFontCmss46
g_sFontCmss46b
const Graphics_Font g_sFontCmss46b
g_sFontCmss46i
const Graphics_Font g_sFontCmss46i
g_sFontCmss48
const Graphics_Font g_sFontCmss48
g_sFontCmss48b
const Graphics_Font g_sFontCmss48b
g_sFontCmss48i
const Graphics_Font g_sFontCmss48i
g_sFontCmtt12
const Graphics_Font g_sFontCmtt12
g_sFontCmtt14
const Graphics_Font g_sFontCmtt14
g_sFontCmtt16
const Graphics_Font g_sFontCmtt16
g_sFontCmtt18
const Graphics_Font g_sFontCmtt18
g_sFontCmtt20
const Graphics_Font g_sFontCmtt20
g_sFontCmtt22
const Graphics_Font g_sFontCmtt22
g_sFontCmtt24
const Graphics_Font g_sFontCmtt24
g_sFontCmtt26
const Graphics_Font g_sFontCmtt26
g_sFontCmtt28
const Graphics_Font g_sFontCmtt28
g_sFontCmtt30
const Graphics_Font g_sFontCmtt30
g_sFontCmtt32
const Graphics_Font g_sFontCmtt32
g_sFontCmtt34
const Graphics_Font g_sFontCmtt34
g_sFontCmtt36
const Graphics_Font g_sFontCmtt36
g_sFontCmtt38
const Graphics_Font g_sFontCmtt38
g_sFontCmtt40
const Graphics_Font g_sFontCmtt40
g_sFontCmtt42
const Graphics_Font g_sFontCmtt42
g_sFontCmtt44
const Graphics_Font g_sFontCmtt44
g_sFontCmtt46
const Graphics_Font g_sFontCmtt46
g_sFontCmtt48
const Graphics_Font g_sFontCmtt48
g_sFontFixed6x8
const Graphics_Font g_sFontFixed6x8
Copyright 2018, Texas Instruments Incorporated