SimpleLink Graphics Library: RadioButton_api
RadioButton_api
Functions
void Graphics_drawRadioButton (const Graphics_Context *context, const Graphics_RadioButton *radioButton)
bool Graphics_isRadioButtonSelected (const Graphics_RadioButton *radioButton, uint16_t x, uint16_t y)
void Graphics_drawSelectedRadioButton (const Graphics_Context *context, const Graphics_RadioButton *radioButton)
void Graphics_drawReleasedRadioButton (const Graphics_Context *context, const Graphics_RadioButton *radioButton)
Detailed Description
Function Documentation
Graphics_drawRadioButton()
void Graphics_drawRadioButton (const Graphics_Context * context, const Graphics_RadioButton * radioButton)
Draws a RadioButton.
Parameters
context is a pointer to the drawing context to use.
radioButton is a pointer to the structure containing the extents of the RadioButton.
This function draws a RadioButton . The RadioButton will contain the image passed in the RadioButton struct.
Returns
None.
References AUTO_STRING_LENGTH, Graphics_RadioButton::font, Graphics_Context::font, Graphics_Context::foreground, g_sContext, Graphics_RadioButton::gap, Graphics_drawCircle(), Graphics_drawString(), Graphics_fillCircle(), Graphics_setFont(), Graphics_setForegroundColor(), Graphics_RadioButton::selected, Graphics_RadioButton::selectedColor, Graphics_RadioButton::text, Graphics_RadioButton::textColor, TRANSPARENT_TEXT, Graphics_RadioButton::xPosition, and Graphics_RadioButton::yPosition.
Graphics_isRadioButtonSelected()
bool Graphics_isRadioButtonSelected (const Graphics_RadioButton * radioButton, uint16_t x, uint16_t y)
Determines if x and y coordinates are contained in RadioButton.
Parameters
radioButton is a pointer to the structure containing the extents of the RadioButton.
x x-coordinate to be determined if is inside RadioButton
y y-coordinate to be determined if is inside RadioButton
This function determines if x and y coordinates are contains inside RadioButton.
Returns
true if x and y coordinates are inside RadioButton, false if not
References Graphics_RadioButton::font, Graphics_RadioButton::gap, Graphics_RadioButton::numbOfChar, Graphics_RadioButton::xPosition, and Graphics_RadioButton::yPosition.
Graphics_drawSelectedRadioButton()
void Graphics_drawSelectedRadioButton (const Graphics_Context * context, const Graphics_RadioButton * radioButton)
Draws a selected RadioButton.
Parameters
context is a pointer to the drawing context to use.
radioButton is a pointer to the structure containing the extents of the RadioButton.
This function draws a RadioButton using the selected parameters.
Returns
None.
References Graphics_RadioButton::font, Graphics_Context::font, Graphics_Context::foreground, g_sContext, Graphics_fillCircle(), Graphics_setFont(), Graphics_setForegroundColor(), Graphics_RadioButton::selectedColor, Graphics_RadioButton::xPosition, and Graphics_RadioButton::yPosition.
Graphics_drawReleasedRadioButton()
void Graphics_drawReleasedRadioButton (const Graphics_Context * context, const Graphics_RadioButton * radioButton)
Draws a released RadioButton.
Parameters
context is a pointer to the drawing context to use.
radioButton is a pointer to the structure containing the extents of the RadioButton.
This function draws a RadioButton using the released parameters.
Returns
None.
References Graphics_RadioButton::font, Graphics_Context::foreground, g_sContext, Graphics_fillCircle(), Graphics_setForegroundColor(), Graphics_RadioButton::notSelectedColor, Graphics_RadioButton::xPosition, and Graphics_RadioButton::yPosition.
Copyright 2018, Texas Instruments Incorporated