SimpleLink Graphics Library: Graphics_Display_Functions Struct Reference
Graphics_Display_Functions Struct Reference
Primitives_api
This structure defines the implementation of a display driver.
#include <grlib.h>
Data Fields
void(*const pfnPixelDraw)(const Graphics_Display *pDisplay, int16_t lX, int16_t lY, uint16_t ulValue)
A pointer to the function to draw a pixel on this display.
void(*const pfnPixelDrawMultiple)(const Graphics_Display *pDisplay, int16_t lX, int16_t lY, int16_t lX0, int16_t lCount, int16_t lBPP, const uint8_t *pucData, const uint32_t *pucPalette)
A pointer to the function to draw multiple pixels on this display.
void(*const pfnLineDrawH)(const Graphics_Display *pDisplay, int16_t lX1, int16_t lX2, int16_t lY, uint16_t ulValue)
A pointer to the function to draw a horizontal line on this display.
void(*const pfnLineDrawV)(const Graphics_Display *pDisplay, int16_t lX, int16_t lY1, int16_t lY2, uint16_t ulValue)
A pointer to the function to draw a vertical line on this display.
void(*const pfnRectFill)(const Graphics_Display *pDisplay, const Graphics_Rectangle *pRect, uint16_t ulValue)
A pointer to the function to draw a filled rectangle on this display.
uint32_t(*const pfnColorTranslate)(const Graphics_Display *pDisplay, uint32_t ulValue)
void(*const pfnFlush)(const Graphics_Display *pDisplay)
void(*const pfnClearDisplay)(const Graphics_Display *pDisplay, uint16_t ulValue)
Detailed Description
This structure defines the implementation of a display driver.
Field Documentation
pfnPixelDraw
void(*const Graphics_Display_Functions::pfnPixelDraw) (const Graphics_Display *pDisplay, int16_t lX, int16_t lY, uint16_t ulValue)
A pointer to the function to draw a pixel on this display.
Referenced by Graphics_drawPixelOnDisplay().
pfnPixelDrawMultiple
void(*const Graphics_Display_Functions::pfnPixelDrawMultiple) (const Graphics_Display *pDisplay, int16_t lX, int16_t lY, int16_t lX0, int16_t lCount, int16_t lBPP, const uint8_t *pucData, const uint32_t *pucPalette)
A pointer to the function to draw multiple pixels on this display.
Referenced by Graphics_drawMultiplePixelsOnDisplay().
pfnLineDrawH
void(*const Graphics_Display_Functions::pfnLineDrawH) (const Graphics_Display *pDisplay, int16_t lX1, int16_t lX2, int16_t lY, uint16_t ulValue)
A pointer to the function to draw a horizontal line on this display.
Referenced by Graphics_drawHorizontalLineOnDisplay().
pfnLineDrawV
void(*const Graphics_Display_Functions::pfnLineDrawV) (const Graphics_Display *pDisplay, int16_t lX, int16_t lY1, int16_t lY2, uint16_t ulValue)
A pointer to the function to draw a vertical line on this display.
Referenced by Graphics_drawVerticalLineOnDisplay().
pfnRectFill
void(*const Graphics_Display_Functions::pfnRectFill) (const Graphics_Display *pDisplay, const Graphics_Rectangle *pRect, uint16_t ulValue)
A pointer to the function to draw a filled rectangle on this display.
Referenced by Graphics_fillRectangleOnDisplay().
pfnColorTranslate
uint32_t(*const Graphics_Display_Functions::pfnColorTranslate) (const Graphics_Display *pDisplay, uint32_t ulValue)
A pointer to the function to translate 24-bit RGB colors to display-specific colors.
Referenced by Graphics_translateColorOnDisplay().
pfnFlush
void(*const Graphics_Display_Functions::pfnFlush) (const Graphics_Display *pDisplay)
A pointer to the function to flush any cached drawing operations on this display.
Referenced by Graphics_flushOnDisplay().
pfnClearDisplay
void(*const Graphics_Display_Functions::pfnClearDisplay) (const Graphics_Display *pDisplay, uint16_t ulValue)
A pointer to the function to clears Display. Contents of display buffer unmodified
Referenced by Graphics_clearDisplayOnDisplay().
The documentation for this struct was generated from the following file:
grlib.h
Copyright 2018, Texas Instruments Incorporated